### ISSUE TITLE
Support `useEnvVars()` in Qwik

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#1147]
### Is your feature request related to a problem?

It would be nice if environment variables could be supported in Qwik. Something similar to [Next.js](https://nextjs.org/docs/basic-features/environment-variables)

### Describe the solution you'd like

Pseudocode of what I have in mind.

```typescript
function useEnvVars(): Record<string, string> {
  return useStore(process.env):
}
```

NOTE:
- The above code needs to be more complicated as multiple calls to `useEnvVars` need to return the same instance

### Describe alternatives you've considered

n/a

**Comment by nnelgxorz** [comment]
This is probably not the best solution as not all hosting platforms are Node environments.

However, Qwik already has a useEnvData() hook that can be used to accomplish what you're needing.

In your project, where render is called (likely root.tsx), add a field called `envData` and give it an object as value with your environment variables `envData: {...process.env}`. 

Then in your Qwik code you should be able to access your environment variable with useEnvData: `let secret = useEnvData().SECRET_KEY;`

**Comment by nnelgxorz** [comment]
Another approach for Qwik City is using the new Platform field on the request object. That is just a matter of adding the hosting provider specific apis to the Platform field in the Qwik City middlewares.

Should be a couple very small PRs.

**Comment by youngboy** [comment]
@nnelgxorz  Really helpful explanation, would be great if add it to document. 

And perhaps need forewarn about usage of causing leaky credentials ENV issues. In SSR mode, Vite env in convenient and accessible everywhere, https://github.com/vitejs/vite/pull/5404

like 
```
useClientEffect$(() => {
  const env = import.meta.env
})
```

will resulting every env key & value exposed to JS files

**Comment by nnelgxorz** [comment]
Agreed on documentation, @youngboy. I can probably get this set up for the starters and add docs this weekend.

**Comment by ersinakinci** [comment]
@mhevery very kindly started this issue here based on my feedback in Discord.

My only contribution is that the way Next.js does it is foolproof--`process.env.MY_VAR` and you're done. Variables are ready from the environment in prod and `.env.local` file in dev. Very convenient and great DX not having to use an additional hook. That's my personal preference.

Also note that Next.js monitors `.env.local` and hot updates the app with the appropriate variables. No need to restart the server. Also excellent DX.

**Comment by nnelgxorz** [comment]
@ersinakinci Can you look over these docs and see if they're closer to what you're looking for? https://docs.astro.build/en/guides/environment-variables/ 

Think I'm going to snoop around Astro's source code since it's built on Vite too.

**Comment by mrmcc3** [comment]
So it seems vite statically replaces `import.meta.env.VITE_` with vars loaded from `.env` in bundles. This all happens at build time.

I guess it could be nice to use the `PUBLIC_` convention to ensure certain variables can only end up inlined in server bundles.

At runtime though it differs based on platform for example.
- node `process.env` (global)
- cloudflare `env` parameter (not global)

Remix Docs have an interesting write up too. https://remix.run/docs/en/v1/guides/envvars

**Comment by nnelgxorz** [comment]
@mrmcc3 Yeah, that's why we added the platform field to the request object, so we can pass platform specific APIs to endpoint handlers.

I was just playing a little and Vite will load any env variables (even ones outside of a .env file) if they're prefixed wih VITE_. Looks like Astro has gotten around this, which is why I want to snoop at their code tomorrow.

Also, you don't have to do this dance of setting up the useEnvData options, you can just call import.meta.env in place of process.env and it will work. Well, besides the prefixing thing.

I'll definitely take a look at the Remix article as well. Thanks for posting it!

**Comment by mrmcc3** [comment]
Yep nice work on the platform field. 

> you can just call import.meta.env in place of process.env and it will work. 

Will import.meta.env work at runtime too? Or is it just a vite build time thing?

**Comment by nnelgxorz** [comment]
@mrmcc3 By runtime do you mean if the environment variable changes in the environment it will update in the code? In that case, I'm not positive. I'll look into it.

**Comment by nnelgxorz** [comment]
One option is to add process to the platform field on the Express middleware. This would keep process out of Netlify and Cloudflare projects, and also enforce the Remix-like restriction that process could only be accessed in 'server code' aka RequestHandlers. Using it would look like:

```typescript
export const onGet: RequestHandler = ({platform}) => {
  let secret = platform.process.env.SUPER_SECRET_KEY;
  // Your code here ...
}
```

A downside here is that all .env handling would have to be re-implemented by Qwik City, instead of relying on Vite's implementation. That might be a worthwhile compromise. Maybe @adamdbradley can mull this over.

I think the ideal solution is using the platform field **and** leveraging Vite's .env implementation.

**Comment by mrmcc3** [comment]
> if the environment variable changes in the environment it will update in the code?

@nnelgxorz Another scenario would be building locally (or on CI) and then deploying to a provider that runs the server with alternate env vars. Or if a preview deployment with one set of vars is promoted to production (alternate vars) without rebuilding.

**Comment by nnelgxorz** [comment]
Hmm. Seems like that would be pretty platform dependent? I know Netlify and Cloudflare both have dev tooling that allows you to keep your local and deploy environments synchronized. Not sure about how the second case would play out without testing it.

**Comment by manucorporat** [comment]
Agree, i dont think this is an api we need at Qwik core, as it’s very build dependant and vite already provides it, also worst case scenario we have the envData escape hatch, that can be used to pass all sort of data.

Lets document it. and recommend `useEnvData()` for common use cases

**Comment by mhevery** [comment]
Sounds like we should close this issue then.

**Comment by Wimpert** [comment]
Hey All,

I would like to share how we are currently handling this, please feel free to comment and share your opinions.

As want to build our app on CI and deploy the same build result to all our environments, we can not rely on [import.meta.env](https://vitejs.dev/guide/env-and-mode.html) since that is statically replaced.

We run our backend in a node env so the environment variables are defined using `process.env.VAR_NAME`.  On the machines of the developers we use a `.env` file:

```
VAR_NAME="var_value"
```

## How do we handle environment variable in code?

So we make use `useEnvData` to handle this but we hide it by writing our own hook over it:

```typescript

export interface CustomEnvData {
  varName: string;
}

export const getCustomEnvData = (): CustomEnvData => {
  if (!process.env['VAR_NAME']) {
    throw Error('no VAR_NAME defined');
  }
  return {
    varName: `${process.env['VAR_NAME']}`,
  };
};
export const CUSTOM_ENV_DATA = 'customEnvData';
export const useCustomEnvData = (propName: keyof CustomEnvData) =>
  useEnvData<CustomEnvData>(CUSTOM_ENV_DATA)?.[propName];
```


### How do we set it in the application?

To set this in the application, we need to add it to the existing `envData` of QwikCity in the `entry.srr.tsx` file:

```typescript
export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
    envData: {
      ...opts.envData,
      [CUSTOM_ENV_DATA]: getCustomEnvData(),
    },
    base: extractBase, // determine the base URL for the client code
    prefetchStrategy: {
      implementation: {
        linkInsert: null,
        workerFetchInsert: null,
        prefetchEvent: 'always',
      },
    },
  });
}
```

Now when a developer needs a variable all it take is:
```typescript
 const customValue = useCustomEnvData('varName');
```
