### ISSUE TITLE
line break in text node not rendering

### ISSUE THREAD

**Issue by youngboy** [BuilderIO/qwik#1214]
### Qwik Version

0.0.108

### Operating System (or Browser)

mac

### Which component is affected?

Qwik Runtime

### Expected Behaviour

the same as html behavior https://stackblitz.com/edit/web-platform-qpz4rp?file=index.html

`white-space: pre`

```
<pre>
line 1
line 2
line 3</pre
>
```

### Actual Behaviour

https://qwik.builder.io/playground#version=0.0.107&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQ3ByZSUzRSU1Q25saW5lJTIwMSU1Q25saW5lJTIwMiU1Q25saW5lJTIwMyUzQyUyRnByZSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQXBwJTIwJTdEJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D

**Comment by manucorporat** [comment]
This is the expected behaviour in jSX, same applies to solid, react, preact...
you need to use a string literal

https://qwik.builder.io/playground#version=0.0.107&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQ3ByZSUzRSU3QiU2MCU1Q25saW5lJTIwMSU1Q25saW5lJTIwMiU1Q25saW5lJTIwMyU1Q24lNjAlN0QlM0MlMkZwcmUlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQXBwJTIwJTdEJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D
