### ISSUE TITLE
Fetching component fails

### ISSUE THREAD

**Issue by Marzdor** [BuilderIO/qwik#1402]
### Qwik Version

v0.9.0

### Operating System (or Browser)

Mac Brave

### Node Version (if applicable)

v16.17.0

### Which component is affected?

Qwik React

### Expected Behaviour

When I click on the icon it switched from the `eyeShow` image to the `eyeHide` image and the input type switched from a `password` to a `text`.

### Actual Behaviour

It crashed with this error. 

```
Failed to fetch dynamically imported module: http://127.0.0.1:5173/src/textinput_component_m6x9g7kxsle.js
```

### Additional Information

Here is a minimal [repo](https://github.com/Marzdor/qwik-icon-bug) built with `npm create qwik@latest` to see the error.

**Comment by manucorporat** [comment]
figured it out! the paths to the images are wrong, it's leading to a very bad error message:
```
https://stackblitz.com/edit/github-dd4xye?file=src%2Fcomponents%2FTextInput.tsx,src%2Fcomponents%2Frouter-head%2Frouter-head.tsx
```

```tsx
import eyeHide from '/eye-hide.png';
import eyeShow from '/eye-show.png';
```
either you use the path directly `src={'/eye-hide.png'}` or make put the images inside src, and import them with a relative path.

I will keep this issue open because we should print a better error.

**Comment by Marzdor** [comment]
Hmm I see, it works when I switch it like this `import eyeHide from "../../../public/eye-hide.png";` 
but in the console it states `Instead of /public/eye-hide.png, use /eye-hide.png.`

Which made me change it to `import eyeHide from '/eye-hide.png';` which seems to break it.

I guess just putting it in the src like this `src={state.showPassword ? "/eye-show.png" : "/eye-hide.png"}` seems to be best option.

**Comment by mglikesbikes** [comment]
@Marzdor — think you're confusing yourself! When you `import eyeHide from "somewhere"` — that's a build-time `import()` call. It's not made in the context of serving a file in a web browser or anything like that, just good ol' javascript trying to find something _on the local filesystem._

Here's what your code means:
- `import eyeHide from './eye-hide.png'` tells the compiler you want that PNG included in your build file, and it's located in the current directory.
- `import eyeHide from '/eye-hide.png'` tells the compiler you want that PNG loaded from the root of your file system — oops! 🤦 

Your best bet to resolve this is going to be creating a new directory inside of `src` — e.g., `src/components/_assets/eye-hide.png`. Then from your `TextInput.tsx` component, `import eyeHide from './_assets/eye-hide.png'`

The reason to move it out of the `public` folder? That folder already gets uploaded as-is and served as static files. Alternately, just change [line 79](https://github.com/Marzdor/qwik-icon-bug/blob/main/src/components/TextInput.tsx#L79) to:

```
src={state.showPassword ? "/eye-show.png" : "/eye-hide.png"}
```

The reason this is okay is because the `src` attribute makes an HTTP call, in the browser, _after_ your site's already built, deployed, and being served. It's a network call, not a build-time filesystem include.

Hope that helps!

**Comment by ahashem95** [comment]
Thanks @manucorporat. Same for me, I was trying to import the SVG file directly and then use it while linking: 

```
import spriteUrl from '/sprite.svg?url';

<svg class='base-svg'>
    <use xlink:href={spriteUrl + '#icon-' + icon} />
</svg>
```


Changing it to the following, solved the issue:
```
<svg class='base-svg'>
    <use xlink:href={'/sprite.svg#icon-' + icon} />
</svg>
```
