### ISSUE TITLE
[DOCS] Deployment guide

### ISSUE THREAD

**Issue by r2musings** [BuilderIO/qwik#1408]
Would really liked to see a Deployment section in the docs that steps through building and deploying SSR and static site not only to edge-capable providers but also to cloud providers like AWS/Azure as Express JS app.

**Comment by alxndr** [comment]
I was thinking about this earlier as well.

Here's my process for using GitHub Pages as the host:

* configure the repo to use Pages
* use the CLI `qwik` command to `add` the static build target
* `npm install --save-dev gh-pages` (yes an npm package with the same name as the Git branch)
* create a task which runs the necessary build task(s) and then uploads the results using [the `gh-pages` package](https://github.com/tschaub/gh-pages)
  * "necessary tasks" appears to mean `npm run build.client && npm run build.static && npm run ssg` (for Qwik 0.9.0 / vite 3.1.3)
  * configure `gh-pages` to use the `dist` subdir, and publish to whatever branch you set up Pages to use in the first step
    * I also have it [tag the commit and use a specific commit message](https://github.com/alxndr/jrad-today/blob/a64ba64e5d2c32db082aa0f14ebf937d9bb1042d/package.json#L15)

**Comment by Gregory-Ledray** [comment]
@alxndr I'm following the steps from: https://qwik.builder.io/qwikcity/static-site-generation/static-site-config/

Which are very similar to your steps. First-time-setup:
`npm qwik add`
In the build pipeline:
```
npm run build.client
npm run build.static
npm run ssg
```

I am deploying to AWS (S3 + CloudFront). The home page works `/` but other routes do not. For example, the component 'test' should be at `/test` but the only way I can access it is via `/test/index.html`.

I have used [this strategy](https://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html) - aka routing 404 requests to `/index.html` - to get my existing Vue site to work, and it looks like that also works for React.

My understanding of this strategy is that it follows this procedure:
1. `/test` is a link clicked from an external website
2. CloudFront sees that `/test` is a 404 so it returns `/index.html`
3. VueJS loads `/index.html` (including the client-side framework), but the URL still says `/test`
4. The router runs and examines the URL
5. VueJS uses client-side rendering to render 

I assume this is not working with Qwik because step (4) does not exist in Qwik City. Is this correct? Do you have any suggestions on how to fix routing here?

**Comment by Gregory-Ledray** [comment]
For now I'm using a [CloudFront function](https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/), but I've only done the simplest of testing to check if this works.
```
function handler(event) {
    // NOTE: This example function is for a viewer request event trigger. 
    // Choose viewer request for event trigger when you associate this function with a distribution. 
    if (event.request.uri.includes('.'))
        return event.request;
    var newURI = event.request.uri;
    if (event.request.uri[event.request.uri.length-1] != '/')
        newURI = newURI + '/';
    newURI = newURI + 'index.html';
    event.request.uri = newURI;
    return event.request;
}
```

**Comment by manucorporat** [comment]
We have new docs about this, closing issue! feel free to open a new one.
