### ISSUE TITLE
[DOCS] Key listener rerenders on client without Syntax Highlighting

### ISSUE THREAD

**Issue by stijlmassi** [BuilderIO/qwik#1421]
**How can the documentation be improved?**

On the docs pages, using any arrow keys when reading a page that includes code snippets, said code snippets will suddenly lose all formatting. This is when viewing in a chrome browser.

**Comment by philwolstenholme** [comment]
I see this when using Cmd + C on Mac (Chrome) to copy the snippet. The formatting is lost which isn't that big a deal, but the font size also decreases quite a bit, which makes the snippet text harder to read.

**Comment by wtho** [comment]
@stijlmassi Can you please change the issue title to something like:
**[DOCS] Key listener rerenders on client without Syntax Highlighting**

Also please modify the description - it's not just arrow keys, it's basically any key.

**Comment by Varixo** [comment]
I can add that the problem is ` window:onKeyDown$={(event: KeyboardEvent)` and it occurs only after building the docs (in dev mode is ok), but I don't know why.

https://github.com/BuilderIO/qwik/blob/414881366af2ae1a2a95536582101c8e24a7f633/packages/docs/src/components/docsearch/doc-search.tsx#L75

Without this everything is fine.
