### ISSUE TITLE
SSG Incremental Static Regeneration

### ISSUE THREAD

**Issue by darko-stoilevski-snk** [BuilderIO/qwik#1626]
### Is your feature request related to a problem?

I would like to not have to rebuild and deploy the front-end each time new data is created in the backend. 

Example:
An e-commerce site, can have items added after the Front-end has been built using SSG.
So the new items will not be accessible until we do a rebuild and redeploy of the front-end.
This is not possible on websites that have lots of content or that content changes or new content to be added regularly, like an e-commerce website.

### Describe the solution you'd like

I would like to build the front-end once with SSG, and when new content is created or modified to update the cache for the changes.

### Describe alternatives you've considered

Next.js have their own solution for this, [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration)

**Comment by jdgamble555** [comment]
So I would say in reality, the [vercel-edge](https://github.com/BuilderIO/qwik/tree/main/starters/adapters/vercel-edge) adapter needs to have an ISR option.  When these things become available in other Servers, they could have it to.

SvelteKit just finished implementing this for [Vercel](https://kit.svelte.dev/docs/adapter-vercel#incremental-static-regeneration).

It's a simple [header](https://github.com/sveltejs/kit/issues/661#issuecomment-1416239434) for the `+page.server.ts`.

This could be implemented using the Vercel [build-output-api](https://vercel.com/docs/build-output-api/v3).

Here is an [example](https://github.com/vercel/examples/tree/main/build-output-api/on-demand-isr).  These functions could be programmed into Qwik.

This is a huge reason a lot of people love NextJS and SvelteKit.  The ISR can almost mimic a static site.  I believe this feature will become extremely important in the next few years.

This could be implemented and usable in:

- routeLoader$()
- Endpoints
- Form actions

Just some ideas,

J

**Comment by BerndWessels** [comment]
I just tried to build a small product with only about 10.000 new pages a day - this is currently not scalable with Qwik SSG.

As a workaround I tried to automatically have a new Qwik app for every 1 million pages on different routes, but that becomes a very painful thing to maintain.

I don't know how Qwik with it's resumability logic would even be able to implement incremental SSG since there is additional JS required with each new page I guess, but it is a definite blocker for serious projects with large amounts of products/articles/blogs/... which increase every day.

I hope @manucorporat can work some of his super special outside the box magic to make it work since I really love Qwik a lot 🥰

**Comment by jdgamble555** [comment]
@BerndWessels Just set cache headers that don't expire in your case.

https://qwik.builder.io/docs/caching/

What I want is the ability to use ISR where you can revalidate the data.

J

**Comment by BerndWessels** [comment]
Thanks @jdgamble555 , I can't see how cache headers would help. If a new product enters the system it will currently be served via SSR until the next full `npm run build` will render it as a static page, right?
I guess almost instant revalidation would be also ideal in cases where the price of a product changes. Caching might be in the way there?
Still trying to wrap my head around how to have Qwik handle large amounts of pages where some of them require updates every now and then in the most efficient way, reducing CPU cycles burned by SSR while still keeping pages up to date.

**Comment by jdgamble555** [comment]
> Thanks @jdgamble555 , I can't see how cache headers would help. If a new product enters the system it will currently be served via SSR until the next full npm run build will render it as a static page, right?

No, the cache headers with server the SSR once, and then cache it.  You can set the cache to save for a year.  It will not be re-rendered with SSR for a year.  Most likely, you will have deployed a new version by then, which will invalidate the cache anyway.  This ends up give you the same result as static files if you set it up right (depends on where you put your cache headers etc).

> I guess almost instant revalidation would be also ideal in cases where the price of a product changes. Caching might be in the way there?

This is what Incremental Static Regeneration is really good at.  It allows you todo `on-demand` cache revalidation on the global level. See [Comparision ISR Vs Cache-Control](https://vercel.com/docs/concepts/incremental-static-regeneration#isr-vs-cache-control-comparison-table).  Currently, I'm only aware of Vercel offering this.  They use Cloudflare under the hood among other custom caching techniques, which I suspect are based on [Cloudflare Purging](https://developers.cloudflare.com/cache/how-to/purge-cache/#purge-by-single-file-by-url).

Either way, Vercel makes this easy, which is why the Vercel Adapter should support this.

J

**Comment by wmertens** [comment]
I too believe that the solution is to put your site behind a cache and use caching headers to indicate what can be "static". Whenever you update prices you clear the cache for those products.

**Comment by jdgamble555** [comment]
This won't work anyway. Vercel implements this in their frameworks, but it uses serverless. Qwik only supports the edge, which frankly I am glad about.  Would be easy to use Cloudflare purging.
