### ISSUE TITLE
Updating a store/signal in a useWatch$ does not update the UI

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#1678]
### Qwik Version

0.10.0 (Also tested on main)

### Operating System (or Browser)

Chrome 106

### Node Version (if applicable)

16

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Updating a store/signal in a `useWatch$` should re-render the subscribed components.

### Actual Behaviour

Updates dont occur

### Additional Information

[Reproduced here](https://stackblitz.com/edit/qwik-starter-naeo4d?file=src/routes/index.tsx)

**Comment by manucorporat** [comment]
This is expected, useWatch$() is returning a promise, this causes the render to wait until the watch finished. What you see it;s just the UI waiting for the watch to finish, the update is visible with the setTimeout() because you are letting the useWatch to finish, and the timeout is changing the value
