### ISSUE TITLE
Revisit $ hook API

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#191]
The `$` signal both developers and the compiler that the first argument needs to be moved. This is important for developers to know, cuz $ functions have special rules.

This discussion is purely a naming discussion and adds to design constraints to the existing one:

## Existing constrains:

- We need to a way to signal a function is special (prefix or suffix)
- It needs to be a suffix, cuz the prefixes are already reserved for (use, on, with, create). adding new prefix would make code hard to read and understand.
- There are always two versions of the same function. One with the signal (the ones that includes the magic) and a second one that takes a QRL directly.
- Compiler magic only applies to the first argument of the function
- No special cases, no function is different (other than different types)
- External developers can create their own custom functions that trigger optimiser magic

## New constrains:

- DX: Make the function with the signal (the magic one), the default one in terms of IDE autocompletion
- DX: Make the function with the signal (the magic one), the default one in typing (make the preferred function to be shorter)
- DX: Double clicking to select the whole identifier breaks with `$`, only selection the text part. From `component$`, only `component` is selected, if double clicking on the identifier.
- Subjetive: `$` has old school smell: angularjs and jquery
- No basic feature needs to use the explicit qrl() mode. Meaning moving components tag name to an options argument at the end.

## Extra constrains?

- Signal suffix === hook function name (`componentXXX()` -> `XXX()`)
- Not magic functions can not end with the name of the hook function. The following is not allowed `componentQrl(qrl())`

## Keywords

- `$`
- `_`
- `qrl`
- `hook`
- `Q`
- `Explicit`
- `External`
- `Inline`
- `Lazy`

## Possible solutions

|  CURRENT:   | `$()`  | `component$()`  | `component()`  |
|-------------|-------|------------------|-----------------|
| 1 | `qrl()`  | `componentQrl()`  | `componentQrlExplicit()`  |
| 2 | `$()`  | `componentQrl()`  | `componentQrlExplicit()`  |
| 3 | `Q()`  | `componentQ()`  | `componentExplicit()`  |
| 4 | `Q()`  | `componentQ()`  | `componentQrl()`  |
| 5 | `Q()`  | `componentQ()`  | `componentFromQrl()`  |
| 6 | `_()`  | `component_()`  | `componentQrl()`  |
| 7 | `_()`  | `component_()`  | `component_explicit()`  |
| 8 | `qrl()`  | `component_()`  | `component_explicit()`  |
| 9 | `$()`  | `component$()`  | `componentQrl()`  |

**Comment by mhevery** [comment]
Every time I look at non-symbol (`$`/`_`) based suffixes, they don't stand out to me enough. Plus with letters, there is the whole uppercase/lowercase difference. For example
```typescript
componentQ(() => null);
component(Q(()=> null);
const myfn = Q(() => null);
```

In the above, it is weird that the `Q()` which is a function is used in uppercase.

I acknowledge that `$` has two issues:
1. IDE sorting order is not ideal (`component` before `component$`) (This could be fixed by suffixing with `_` as in `component_()`)
2. A lot of people may have an allergic reaction to it due to jQuery and AngularJS.

# `Q()`/ `componentQ()`/`compontentFromQRL()`

1. `compontentFromQRL` is a mouthful. I think that `compontentFromQRL` will be a lot more common than you realize.  Perhaps not for `component` but for `useMyLibraryFromQRL` so I am really not liking anything which requires long complex suffixes.
2. You can have existing API names which contain `Q`. This will make it hard on the eye to be sure that it is special. The nice thing about `$` is that it will really stand out and makes it clear to the developer what is going on.

Counterpoint: `$` is used in streams. Yes, but that is unlikely to be used with Qwik as streams do not serialize. (Even if they are used it will not confuse the optimizer because only function invocations are translated (not just symbol with `$` suffix). So `foo$` will not be translated only `foo$()`, and the latter is never used with streams.)

**Comment by manucorporat** [comment]
Fixed with https://github.com/BuilderIO/qwik/commit/0b247ca0a2708c804ac5a469814d68e97f54c60a
