### ISSUE TITLE
Add qwik add command for Cypress

### ISSUE THREAD

**Issue by jordanpowell88** [BuilderIO/qwik#1926]
### Is your feature request related to a problem?

Currently, playwright is the default E2E testing solution. However, Cypress has a very strong end to end user base and is the default in many other frameworks. It would be great to allow users the option to use Cypress as an alternative 

### Describe the solution you'd like

Something like `qwik add cypress` would remove playwright, add cypress package and configure.

### Describe alternatives you've considered

This could be left for users to do but this is a less than ideal DX in my opinion

**Comment by manucorporat** [comment]
I dont think we even have a official support for playwright, I know for a fact that some community member was working on it though

**Comment by jessezhang91** [comment]
@manucorporat is there any interest in adding cypress?

i've added this for my project and have managed to do some things with global-agent http proxy to get SSR utilizing cypress intercepts (for mocking in functional tests). happy to find some time to contribute this back to qwik if there is interest here!

**Comment by zanettin** [comment]
Hi @jessezhang91 👋 

Just wanted to let you know about a community project regarding your request. @shairez (community DevRel. of qwik) and other community members are working on this over here https://github.com/qwikifiers/cypress-qwik 🎉 

I'll close this issue because the core team decided to offer this as a community plugin and not integrate it into the core atm.

**Comment by shairez** [comment]
Thanks @zanettin 

I'm re-opening this because once cypress-qwik is stable we can add an `add` command here that will install it (it doesn't have to be part of qwik, but just an integration, just like playwright and vitest)

So once the PR will be merged we could close this

And @jessezhang91 we'd love to have you join as a collaborator, DM me on discord if you're interested
Thanks!

**Comment by manucorporat** [comment]
Fixed by @shairez !

**Comment by shairez** [comment]
Aure thing @jordanpowell88 
It was a team effort with @manucorporat 🙌

And thanks for helping with this plugin 🙏
