### ISSUE TITLE
Site is live but without any CSS styling Cloudflare Pages built

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#1928]
### Qwik Version

0.12.1

### Operating System (or Browser)

Windows

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

regular CSS after built

### Actual Behaviour

Site is live but without any CSS styling.
The only midification with starter is 2nd line in japanese with a HTML <ruby> tag for testing.
![eslint-problem-on-windows](https://user-images.githubusercontent.com/14911996/198970582-71e97249-e582-484d-9705-c3c9d4c9f7ca.jpg)

### Additional Information

Everything is working fine with vite in Dev.

**Comment by tidiview** [comment]
ADDITION TO PREVIOUS:
in `link` styling tags of `head` like following:
`<link rel="stylesheet" href="/src/global.css">`,
CSS validator says:
`missing type="text/css"`,
therefore, it should be:
`<link rel="stylesheet" href="/src/global.css" type="text/css>`,

I tried to add that to `router-head.tsx` but had not been able to have it changed on build > strange...

**Comment by zanettin** [comment]
Hi @tidiview 
Thanks for mentioning this 🙏 

I am running a demo page as well on cloudflare pages using qwik `0.12.1` and on my side everything looks fine 👍 

I've attached you my html `<head>` content as well as my cloudflare page config. 
My current suggestion would be to check your `vite.config.ts` file on the root level if you started the project before `0.12.0` since then the new adapters have been released.

### my root vite config content
```
import { defineConfig } from "vite";
import { qwikCity } from "@builder.io/qwik-city/vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig(() => {
  return {
    plugins: [
      qwikCity(),
      qwikVite(),
      tsconfigPaths(),
    ],
  };
});
```

### cloudflare
<img width="643" alt="Bildschirmfoto 2022-11-01 um 23 03 24" src="https://user-images.githubusercontent.com/3241476/199351384-e1dad336-3570-4285-93a9-c95a40542024.png">

### PoC html head
<img width="698" alt="Bildschirmfoto 2022-11-01 um 23 06 16" src="https://user-images.githubusercontent.com/3241476/199351390-92c17d90-6480-4256-8e4b-2e52a815887c.png">

i hope this brings you further.

**Comment by romainsimoes** [comment]
I had the same issue and I was missing some new config files.
I just launched the `npm run qwik add cloudflare-pages` command again and it was fixed.

**Comment by adamdbradley** [comment]
Should be fixed in the latest release, thanks for opening the issue.
