### ISSUE TITLE
Why not base Qwik's serialization on Rich Harris' devalue library?

### ISSUE THREAD

**Issue by Evertt** [BuilderIO/qwik#2044]
### Is your feature request related to a problem?

I'm reading the docs of Qwik and I read this:

> Limitations of JSON which Qwik solves:
> * ...
> * JSON can't serialize some object types. For example, DOM references, Dates, etc... Qwik serialization format ensures that such objects can correctly be serialized and restored. Here is a list of types that can be serialized with Qwik:
DOM references
Dates (not yet implemented)
Function closures (if wrapped in QRL).

And I thought, *"Dates not implemented yet? But Rich Harris' `devalue` has already implemented that, and even more objects like `Map` and `Set`. So why not use that package and expand on it?"*

And then finally it says Qwik can't serialize classes, which admittedly `devalue` also can't. However, I'm confident that serializing classes shouldn't actually be that hard. As long as you enforce those classes to implement an interface that exposes two methods for serializing and unserializing.

### Describe the solution you'd like

Either install `devalue` as an npm dependency and then import it, alter its prototype to include the features Qwik needs and re-export it. Or just port the code over, if the license allows for that.

Then it would also be nice if classes could be (un)serialized, which I think should be possible as long as the classes implement an interface with the two methods `serialize<T>(): T` and `unserialize<T>(data: T): this` or something along those lines.

### Describe alternatives you've considered

I haven't considered any alternatives.

**Comment by manucorporat** [comment]
Qwik serialization is way more advanced and optimized for our use case, no value in using an external library we cannot control. 

Supporting extra serialization is a more complex then you imagine, Qwik deserializes before it even downloads any of your code, so supporting custom serializators is not as easy as adding a class with a prototype, because we would have to execute that code.

Here you can find all the serializers, we can add more if you are missing core objects that are not implemented:
https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/container/serializers.ts
