### ISSUE TITLE
WithLocale error qwik/qwik city

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#2081]
### Qwik Version

0.12.1 qwik city 0.0.120 both current latest versions

### Operating System (or Browser)

All

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

Dev mod should work and build should succeed

### Actual Behaviour

Qwik city is trying to import something that is not exported by qwik

### Additional Information

https://stackblitz.com/edit/qwik-starter-4km3k8?file=package.json

Try to run npm start, npm run build, or npm run build.client to reproduce

**Comment by IlyasShabi** [comment]
You’re right the package `@builder.io/qwik: "^0.12.1"` do not expose `getLocale`, this function was recently added in this [commit](https://github.com/BuilderIO/qwik/pull/1594/files#diff-1598b16ba9b934c96a66eec6864b1f7c5566488c34f44b0abc1664f97da5ac12R8) but I think this will be fixed by releasing a new version soon

**Comment by manucorporat** [comment]
Should be fixed already! make sure you update to latest Qwik: 0.13.3!
