### ISSUE TITLE
Remove component$ from component declaration

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2106]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

React has made it easy. Declare a simple JavaScript function. If it returns object and its name starts with `use` then it's a hook. If it returns JSX it's a component.

For each Qwik component I need one line of boilerplate code, and a function call boilerplate code:

```
import { component$ } from '@builder.io/qwik`

const Menu = component$(() => {
````

Compare it to React:

```
// no import

const Menu = () => {
```

For a project that has more than 100 components, and for a company that does tens of projects per year, that means thousands of boilerplate codes.

Since you have already made the decision to make things more familiar for React developers, please remove these boilerplate codes.

Thank you

### Describe alternatives you've considered

No alternative

**Comment by manucorporat** [comment]
Qwik takes advantage of the `$` in the component function to achieve resumability and only download the parts of the code that are interactive. https://qwik.builder.io/docs/advanced/dollar/

need to close this issue, since this is not a proposal of HOW to remove it, we are not aware of any way we can possible remove it technically.

Thanks for the issue :)
