### ISSUE TITLE
Since everything is lazy loaded and we don't have any other option, then remove dollar signs altogether

### ISSUE THREAD

**Issue by hosseinitabar** [BuilderIO/qwik#2119]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

In [this](https://youtu.be/aGuJPcIdX0A?t=1264) YouTube video, Misko explains that **everything** is lazy loaded. The component and the listeners.

And he says that the dollar sign is part of the API so you can never forget it and if you don't put it there the compiler yells at you.

But from the other hand, having so much dollar signs in code reduces code readability. After all, it's yet another character that is not familiar to eyes.

And, it's also a boilerplate character.

If **everything** is lazy loaded by design, then why not remove the `$` from every API ending? That way code becomes much cleaner. And portability of React apps to Qwik would also increase. Developers can copy/paste their listeners verbatim into their new Qwik app.

### Describe alternatives you've considered

I wanted to barrel out the dollar sign for components:

```
// index.tsx
import { component$ as component } from '@builder.io/qwik'

export { component }
```

And put this barrel in my `vite.config.ts` as an alias.

Then in my components I would be cleaner:

```
import { component } from 'qwik'

const Foo = component(() => {})
```

**Comment by zanettin** [comment]
Great answer @jordanw66. Another thing i wanted to mention are the `lite components` (https://qwik.builder.io/docs/components/lite-components/#lite-components). With the `$` you as a developer have the power to decide whether you'd like to have a single chunk for your component or if it should be bundled together with a parent.

**Comment by shairez** [comment]
Thanks for opening the issue and trying to make Qwik's DX better @hosseinitabar !

perfect answer @jordanw66 , thanks!
and thanks for the addition @zanettin 

Removing the $ signs is not an option for the foreseeable future, as Jodrdan wrote - because of it's implications on the Qwik optimizer plus its use as a signal for devs that this code is being extracted.

Personally I too asked myself the same question when first looking at Qwik code, but after I've built a few stuff with it, I got used to it pretty fast.

So because just removing it is not an option, I'm closing this issue for now

But... we would always love to hear more suggestions of how to improve the DX, so if you'll have ideas for other alternatives to $ that still respect the same constraints Jordan wrote about, please re-open this issue or open up a new one.

Thanks again! 🙏
