### ISSUE TITLE
Css siblings has issue with a component inline style tag

### ISSUE THREAD

**Issue by tuurbo** [BuilderIO/qwik#2141]
### Qwik Version

0.13.3

### Operating System (or Browser)

chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour
All boxes should be the same height in the example stackblitz.

### Actual Behaviour

A style tag is inserted inside one of the <Icon/> components via useStyles$. This can cause css classes that use sibling modifiers to count the style tag as a sibling as shown below. 

see  https://stackblitz.com/edit/qwik-starter-krkkoj?file=src%2Froutes%2Findex.tsx

### Additional Information

Can this issue be fixed by Qwik inserting the style tag into the document head?

**Comment by manucorporat** [comment]
Thank you so much for the PR! unfortunately we cant add the styles to the head during SSR without disabling streaming completely!

Qwik can SSR faster than most frameworks because it's rendering architecture allows to put into the network the bytes as soon as they are rendered. A component cant easily modify the head, cuz it's already been sent to the browser!

However the proposed alternative is a good idea, and already prepared a PR!
