### ISSUE TITLE
Link component throws an error if the immediate child directory of route is dynamic

### ISSUE THREAD

**Issue by shiroinegai** [BuilderIO/qwik#2205]
### Qwik Version

0.0.123

### Operating System (or Browser)

Windows 10 Pro 21H2 Firefox 107

### Node Version (if applicable)

18.11.0

### Which component is affected?

Qwik City

### Expected Behaviour

Link component with `href="/flower"` should correctly navigate on click.

### Actual Behaviour

On hovering over or clicking the link, the following error is produced in the browser console:
`Uncaught (in promise) TypeError: error loading dynamically imported module`

### Additional Information

Minimal reproduction:
https://stackblitz.com/edit/qwik-starter-legvvv?file=src/routes/index.tsx

Reverting qwik-city to 0.0.122 or nesting the directory one level lower under a static directory fixes the issue.

**Comment by thekip** [comment]
Having the same issue, I will add couple of my findings: 

## STR

Create a root segment in routes folder with param, `[lang]` for example. 
<img width="207" alt="image" src="https://user-images.githubusercontent.com/1586852/203043401-46090e68-5aa4-4708-90a7-4757a9eff20d.png">


## Root Cause
This "catch-all" parameter catches qwik's metadata requests, and there is no way to add an exclusion. 

In our case, we're trying to implement dynamic i18n and root segment of the route is `[lang]`. This route catch all assets such as `/image.png` as well as `@quick-city-plan`. 

## Proposed solution: 

 1. To directly address this issue should be a way to set a regexp for route param, something like in different meta-framework, so you can narrow matching and avoid this issue. 
 2. Make assets always resolve first than routes, kinda `try_files` directive in nginx
 
Currently, we workaround this issue by creating symlinks for a folder on different languages: 

<img width="243" alt="image" src="https://user-images.githubusercontent.com/1586852/203042454-16802276-8224-44e4-b387-6fe1709b8ebd.png">
