### ISSUE TITLE
Qwik + React + MUI - checkboxes are not updating on state change

### ISSUE THREAD

**Issue by mrzepinski** [BuilderIO/qwik#2215]
### Qwik Version

0.13.3

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

16.6.0

### Which component is affected?

Qwik React

### Expected Behaviour

React MUI checkboxes should react as the Qwik ones.

There is another thing on React MUI usage - we could have API to provide React elements like: `secondaryAction` for the https://mui.com/material-ui/api/list-item/ component. Using Qwik we can't provide there the React component because then Qwik starts to complain and we can't provide there a React component as then Qwik starts to complain.

### Actual Behaviour

Hi Qwik community!

Stackblitz example: https://stackblitz.com/edit/vitejs-vite-ncbtdf

How to properly update the React MUI component to make checkboxes reactive?
As Qwik-made checkboxes work as expected, React MUI qwikified ones are not updating but the whole component tree seems to be re-rendered.

### Additional Information

![qwik-react-mui-checkboxes](https://user-images.githubusercontent.com/435196/202999035-72420e70-07cf-462e-a8c9-44c7f192c719.gif)

**Comment by manucorporat** [comment]
Added a full new section in the docs about the limitations: https://qwik.builder.io/qwikcity/integrations/react/#limitations

- First, qwikified components are not interactive by default, need to look into the section "add interactivity". This is because puts this react components in the browser without any JS.
- Second, i noticed a pattern that goes against the whole island architecture: https://www.patterns.dev/posts/islands-architecture/

Hope this helps!
