### ISSUE TITLE
[📖] Doc Diffs?

### ISSUE THREAD

**Issue by neuro-bro** [BuilderIO/qwik#2257]
### Suggestion

Love the work you guys are doing and the pace it is happening but one issue I have noticed is keeping up to date with changes that are tied into lib updates. I have seen them somewhere but it's not obvious and not clear which version of the lib released them. It would be good to have the documentation have a way to handle diffs based on package.json updates. That way, any new features that you guys push (or breaking changes etc.) could be linked between NPM releases and documentation updates so we can see exactly what changed and exactly how to implement the new features or remove depricated ones (I know the console displays deprication pretty well but having docs tied to features would be extremely useful. Especially for beginners.)

**Comment by wtho** [comment]
Maybe have a dropdown on the documentation website with the last, current and a "next" version? Would be some work to set that up. To display all changes from last commit/version would be even more difficult though.

I had the issue that documentation changes are immediately updated, but the lib didn't include these changes yet. Was like that for a long time with the removal of `mutable`.

**Comment by shairez** [comment]
Those are good suggestions @neuro-bro and @wtho !

I think this should be a must for after 1.0 (and I saw Manu already added the label for it)

if any of you want to contribute a PR that "generates" the docs in a "versioned" folder and a pointer to the latest - that's one way I thought about achieving that.

but again, because things are changing rapidly now, I believe it'll be lots and lots of docs generated, so it's best to do it post 1.0 when the breaking changes will be few and far apart.
