### ISSUE TITLE
[🐞] Page back/forward does not refresh the page

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#2378]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have simple counter: when the user increment it, I update the counter and a param in URL to make the state consistent:

```
  const loc = useLocation();
  const nav = useNavigate();

  const state = useStore({ count: loc.query['count'] ? parseInt(loc.query['count']) : 0 });

  const update$ = $(() => {
    state.count++;
    nav.path = '?count=' + state.count;
  });
```
After a few increments, the user hits the back key: _the URL is updated, but the page is not._

### Reproduction

https://stackblitz.com/edit/qwik-starter-fcaxxx?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

- In StackBlitz repro, press` Open in New Tab`
- Press `Increment` a few time
- Press page back in the browser

The URL is updated, but not the page

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.15.2 => 0.15.2 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    vite: 3.2.4 => 3.2.4
```

### Additional Information

As a workaround, I can handle the pop state adding:
```
useClientEffect$(() => {
    window.onpopstate = (event) => {
      if (event) window.location.reload();
    };
});
```

What I'm wondering is if this is the expected behavior, or if this recent fix (https://github.com/BuilderIO/qwik/pull/2263) should handle this case as well.

Thanks

**Comment by cmbartschat** [comment]
I made a small tweak to your project to hopefully show what is going on: https://stackblitz.com/edit/qwik-starter-eblr4p?file=src/routes/index.tsx

Since your component had no logic to respond to location changes after the fact, you have a few options.

I added an example `useWatch$` that allows you to use the state as the source of truth, but still keeps it in sync with the location, or possibly you don't need state.count at all.

**Comment by robisim74** [comment]
Thanks for your suggestion, but the app implementation logic should be changed just to handle the page back. Furthermore, the `useWatch$` action is fired every time, and not only during the page back.

After the above commit by @adamdbradley, if  `Link` is used to update the URL, the following script is injected on client:

```
import {CLIENT_HISTORY_INITIALIZED} from "/node_modules/@builder.io/qwik-city/index.qwik.mjs?v=07612a8b";
import {POPSTATE_FALLBACK_INITIALIZED} from "/node_modules/@builder.io/qwik-city/index.qwik.mjs?v=07612a8b";
export const Link_component_useOnDocument_u0YVoxt2aTY = ()=>{
    if (!window[POPSTATE_FALLBACK_INITIALIZED]) {
        window[POPSTATE_FALLBACK_INITIALIZED] = ()=>{
            if (!window[CLIENT_HISTORY_INITIALIZED])
                location.reload();
        }
        ;
        setTimeout(()=>{
            addEventListener("popstate", window[POPSTATE_FALLBACK_INITIALIZED]);
        }
        , 0);
    }
};
```

Should this also cover this case? and should it also do it in case `navigation `API is used instead of `Link`?

**Comment by billykwok** [comment]
Looks like #2394 doesn't completely fix the issue reported here. There is no `<Link />` component in the example given, so the added reload logic doesn't even get triggered.

Also, "reloading the page when client history is not initialized" does not seem related to the original issue. I think the original issue is that, even when client history is initialized, Qwik City does not re-render the page despite updating the URL, page title, etc

It can be replicated with just the Qwik Starter example.
1. Open the homepage
2. Click the flower Link
3. Refresh the flower page manually and wait for a few second
4. Hit back button

The expected behavior should be that the homepage is displayed again via re-rendering (without a hard refresh). But at least in 0.1.0-beta9, the page content is not re-rendered even though the router seems to be aware of the route change (since the page title is indeed updated).
