### ISSUE TITLE
[✨]

### ISSUE THREAD

**Issue by TimSusa** [BuilderIO/qwik#2447]
### Is your feature request related to a problem?

Am I right, that every function component is supposed to be wrapped by hand into a $component? That seems to make overhead in my opinion.

### Describe the solution you'd like

Every function component is automatically wrapped by the framework or 

### Describe alternatives you've considered

a react hook can be used as alternative.

### Additional context

PS: Huge RESPECT for all of your work to the creator of this @mh. I like the idea behind, as it seems kind of thing that flashes my mind since some long time ago. 

_No response_

**Comment by shairez** [comment]
Thanks @TimSusa 

The component function is `component$` (you cannot import just `component` because it's not part of the API)

So it's automatic.

Its closue `component$( () => { ... } )` does not have to be wrapped in a $

Only functions which leave outside the component and needs to be shared across lazy loaded boundaries need to be wrapped in a $ and the problem of making it automatic is that there's an overhead to extract anything inside the $ so the optimizer wouldn't know which functions to extract and which are just regular functions.

Thanks for taking the time to submit this issue
As this isn't going to change in the forseeable future I'm going to close this for now, but feel free to re-open it if you think otherwise

🙏
