### ISSUE TITLE
[🐞] Error when navigating from component rendered using <Resource> via <Link>

### ISSUE THREAD

**Issue by thealanreis** [BuilderIO/qwik#2812]
### Which component is affected?

Qwik City (routing)

### Describe the bug

**Component 1** :  onGet method which returns a sample json from "https://jsonplaceholder.typicode.com/posts/1", the article title is rendered using resource
Click <Link> to go to **Component 2**:

TypeError: Cannot read properties of undefined (reading 'title') when navigating to another route.

### Reproduction

https://github.com/thealanreis/qwik-bug

### Steps to reproduce

1. git clone https://github.com/thealanreis/qwik-bug
2. cd qwik-bug
3. npm install
4. npm start
5. Open http://localhost:5173/test1
6. Click header link to Link 2
7. See error in the console

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 25.16 GB / 31.28 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
  npmPackages:
    @builder.io/qwik: 0.17.2 => 0.17.2 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    undici: 5.16.0 => 5.16.0 
    vite: 4.0.4 => 4.0.4
```

**Comment by shairez** [comment]
might be related to #2254

**Comment by thealanreis** [comment]
I think it's a different issue since I'm not using useContext();

**Comment by shairez** [comment]
BTW, a cool trick for repros is to add `pr.new/` instead of `github.com/` to the name
it opens it up in a stackblitz environment where one can simulate the bug more easily

https://pr.new/thealanreis/qwik-bug

I'm trying to reproduce it but I'm getting a different error :

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

and can't reproduce the error you reported (maybe it's because it's on stackblitz)

**Comment by thealanreis** [comment]
> BTW, a cool trick for repros is to add `pr.new/` instead of `github.com/` to the name it opens it up in a stackblitz environment where one can simulate the bug more easily
> 
> https://pr.new/thealanreis/qwik-bug
> 
> I'm trying to reproduce it but I'm getting a different error :
> 
> ```
> Failed to load resource: the server responded with a status of 404 (Not Found)
> ```
> 
> and can't reproduce the error you reported (maybe it's because it's on stackblitz)

Whoa, thanks for the tip.

Was able to reproduce using StackBlitz:
1. Open https://pr.new/thealanreis/qwik-bug
2. Click Test1
3. Click Test2

![image](https://user-images.githubusercontent.com/52210220/216694690-e93b2a94-a4a9-4880-85ff-c31da7a32c65.png)

**Comment by shairez** [comment]
thanks I'm able to reproduce it now as well

Yeah so it isn't related to the other issue I mentioned as it's not tree shaking dynamically the missing thing.

It appears to be more like a cleanup issue

@manucorporat from debugging it a bit it looks like the change of the `path` value (which is a signal) causes the component that is suppose to get "unmounted" to be marked for re-renderring, which isn't suppose to happen because it's suppose to get destroyed. 

But there's a `useTask$` on the `QwikCityProvider` that is tracking `navPath.value` that might cause this re-render 

![image](https://user-images.githubusercontent.com/1430726/216769775-b6fe66fc-e620-487f-b10b-7722fbbf870d.png)


![image](https://user-images.githubusercontent.com/1430726/216770940-3730f124-182f-4fd1-8d79-1b6a480c67f3.png)


This might be solved by the latest changes, but I'm not sure
