### ISSUE TITLE
[✨] SUGGESTION: change `createContext` to `createContextToken`

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#2859]
### Is your feature request related to a problem?

`createContext` gives the impression that the actual context is being created when you run it
but in fact, it's just a token to be used by `useContextProvider` which is what actually "creates" the context

I think it'll be easier to show the intent of the function better

And prevents confusing explanations as these: 

![image](https://user-images.githubusercontent.com/1430726/217260401-8874ad6e-d15e-4b67-989f-f175bcaf898d.png)

### Describe the solution you'd like

rename to `createContextToken`

### Describe alternatives you've considered

leaving it as is

I know react has this concept but there you create a component with a provider built in etc, it's not just the context token, so I think it's OK to add the extra characters that come with the word `token` to make things clearer

### Additional context

I can create a PR for it if you think it's a good idea

WDYT @manucorporat @adamdbradley @mhevery ?

**Comment by manucorporat** [comment]
So, Solid, React createContext() creates the "token" not the provider:
https://beta.reactjs.org/reference/react/createContext
https://www.solidjs.com/docs/latest#createcontext

I dont see any conceptually difference, we dont provide: `<Context.Provider>` but we could eventually

**Comment by zanettin** [comment]
just my two cents: it would make sense since the docs already states pretty clear, that it is not a context but "just" an identifier which is returned. not sure whats the plan with the further evolution of it and if the thing @manucorporat  mentioned is planed, it would be legit to keep it. otherwise @shairez 's suggestion would match better imo.

**Comment by manucorporat** [comment]
Is it worth the breaking change + diff with solid/react?

**Comment by manucorporat** [comment]
I would rather call it `createContextId()`, than token, but idk

**Comment by manucorporat** [comment]
>I know react has this concept but there you create a component with a provider built in etc, it's not just the context token, so I think it's OK to add the extra characters that come with the word token to make things clearer

We could eventually do this too, conceptually we are still very similar

**Comment by shairez** [comment]
createContextId is also better than "createContext"IMO

Plus it's best to do this deprecation now rather than later.

In terms of react / solid... I don't think it's the same thing as theirs (because their token hold up more things) so I rather the apis be more self explaining which makes them more teachable at the same time.

Just my POV

**Comment by manucorporat** [comment]
I am not sure it's much better to justify this change now.

**Comment by KenAKAFrosty** [comment]
My first time using Context in Quick did feel a little clunky due to this. It didn't click as easily because it felt like I should've been _creating the context_

If someone's journey is from React or any others, the difference is still sensible because of the very fact it's more self-explanatory.

I prefer Id over Token as well though.

I don't think it should be a breaking change. Probably best to leave the current syntax as a deprecated alias. The deprecation warning in the IDE will also serve the purpose to clarify.

**Comment by shairez** [comment]
yeah, both me and @nnelgxorz got confused as well when working on qwik-ui and trying to understand when exactly is the context being attached to the DOM tree

it took us some time (and reading of the Qwik source code) to understand that we can use `createContext` outside of a component because it's just a token / id and not the actual context

@manucorporat I can do the work of the PR to save you guys the time
I think `createContextId` is also a good name - it will make it more intuitive IMO

WDYT?

**Comment by manucorporat** [comment]
The PR should be small enough, lets do it, but I don’t promise merge yet, need to discusse it

**Comment by shairez** [comment]
Here it is #2898 (will resolve the build issues, but in terms of code changes it's good)

@manucorporat how do you feel about changing the returned type `Context` to `ContextId`?

**Comment by shairez** [comment]
fixed by #2898
