### ISSUE TITLE
[✨] Strip non serializable fields from Loaders/Actions results

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#3019]
### Feature

In loaders/actions it can happen that the developer wants to return an object which is not fully serializable, for example in a project I want in the browser to receive the request sent to the server and for that I have the following:
![Screenshot 2023-02-17 at 17 39 27](https://user-images.githubusercontent.com/61631103/219733569-e55dc6bf-7e00-49a7-a3b8-52c2da689793.png)

Which basically returns the request after stripping away all non serializable fields from the request object.

I can see the need to do this sort of thing often and have lots of `JSON.parse(JSON.stringify(...` in significantly large applications.

So I was just wondering, could the framework itself strip away non serializable fields from a provided object?

### A possible solution

Doing something like `JSON.parse(JSON.stringify(...` inside qwikCity under the hood so that developers don't need to, although it is important to note that also return types should be updated accordingly (which might be tricky)

### Extra

I am not sure if this is a good idea and if stripping away non serializable fields from objects could cause confusion to developers... I just figured I could open anyways the issue to see the reaction to this idea 🙂

**Comment by manucorporat** [comment]
We cant do this automatically, we are effectively changing the object. I would say it's a bad practice to pass everything just in case you need it, we dont want to hide this cost.

Pass what only what you need.

Why are you passing the request as a loader??

**Comment by manucorporat** [comment]
I would say the big problem os this idea is that it break the type checker

**Comment by adaliszk** [comment]
The primary use case where I have seen this parsing trick was to serialize data objects with recursive references to themselves or other objects in a circular manner. This usually happens because it is handy to have such references, but they often cause these objects to be non-serializable.

While the `JSON.parse(JSON.stringify(...` may look tempting, I have seen it impact the performance quite a lot, especially with more significant objects. It essentially abuses the default receiver on the stringify method in that it will omit fields, however, it goes through every key value in all depths, even if your object is mostly serializable. The problem is that the amount of time it needs to remove fields is much less than the time it needs to do nothing and yet have multiple type checks within each cycle.

As mentioned by @manucorporat, often the reason I ran into for using such a solution was the "just in case" or "it is simple"; but such approaches cause massive multiple thousand dollars of bills in bandwidth usage alone while keeping the compute bills seemingly high when the code is "simple". Adding the downside of the type checker, you end up having a solution that is slow and lies to you.

The better approach is to either map a new object with the fields you want or adjust the class - or create a new one - with a `toJSON()` method that can implement any complex logic and return a mapped new object for JSON.stringify.

**Comment by dario-piotrowicz** [comment]
> We cant do this automatically, we are effectively changing the object. I would say it's a bad practice to pass everything just in case you need it, we dont want to hide this cost.
> 
> Pass what only what you need.
> 
> Why are you passing the request as a loader??

I'm passing the request as I want to use its url for the document head.

But yeah, you're totally right I should just pass the url instead of the whole request... I can't precisely remember why I did that, it could either be because I thought I might need more info from the request in the head function or maybe it is because I am used in js to pass objects around since it is very cheap. :sweat: 

About hiding the cost you're also right, so actually yeah I think my suggestion here isn't really a valid one, sorry about that :bow:

**Comment by dario-piotrowicz** [comment]
@adaliszk thanks for you input as well :smiley: 

Yeah both you an Manu are totally right, and this indeed needs to fall on the shoulders of devs that should know and pass clearly just what's needed (and serializable)
