### ISSUE TITLE
[📖] Missing scrollbar in examples section of the docs

### ISSUE THREAD

**Issue by Balastrong** [BuilderIO/qwik#3040]
### Suggestion

I think a scrollbar is missing from the examples page (not related to a specific example): https://qwik.builder.io/examples/introduction/hello-world/

The left menu where all the examples are listed (Hello World, Runtime-less) does not have a scrollbar and the content is cut.
The App panel seems cut as well, I was expecting to see the full clock after scrolling to the end of the demo.

I'm on a MacBook Air 13''

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7253929/219972392-6efe3266-5133-4fc6-87a3-3dddd062fcba.png">

**Comment by zanettin** [comment]
Hi @Balastrong 👋 
Thanks for mentioning this 🙏 Looks like the calculations for the heights of the containers are messed up and needs some adjustments. IMO a perfect chance for new contributors ❤️ 
Thanks again for creating this issue!

**Hint**
adjusting the `.example` class and use `left:0`, `right:0` and `bottom:0` instead of `width` and `height`.
in addition we should make sure, that the `repl` column is not using more than 100% width (check 768px till 1033px screen width) so that the scrollbars of the repl content is also visible.

**Comment by georgeiliadis91** [comment]
Hello, i opened a PR for this, its my first one here and I am not comfortable with the commiter thingy. It shows a proper formatted msg on the commit file but somehow it seems wrong in the github ui. 

If this not up to par please let me know, so I can make adjustments. Cheers !
