### ISSUE TITLE
[🐞] Why can't I use routeLoader$ on my 404 page?

### ISSUE THREAD

**Issue by MiguelValdez-mv** [BuilderIO/qwik#3882]
### Which component is affected?

Qwik Runtime

### Describe the bug

I have a 404 page on which I want to use `routeLoader$` to check there if a user is authenticated or not. The problem is that I can't do it because I get the following warning/error:

`routeLoader$() can only be declared in layout.tsx, index.tsx and plugin.tsx inside the src/routes directory, instead it was declared in "....... /src/routes/404.tsx" .`

As you can see, my 404 page is located in the `src/routes/404.tsx` directory and has the following structure:

```
export const usePageData = routeLoader$(() => {...});

export default component$(() => {
   const { value } = usePageData();

   return <NotFoundPage {...value} />;
});
```

Is it normal for this to happen? What other alternatives do I have?

### Reproduction

https://stackblitz.com/edit/qwik-starter-gjisr5?file=src/routes/404.tsx

### System Info

```shell
System:
    OS: Linux 5.11 elementary OS 6.1 Jólnir
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 976.92 MB / 7.12 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 110.0.5481.100
    Chromium: 112.0.5615.49
  npmPackages:
    @builder.io/qwik: 0.100.0 => 0.100.0 
    @builder.io/qwik-city: ~0.100.0 => 0.100.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by JustinMorritt** [comment]
I think since the 404 pages are statically generated at build time ([seen here](https://qwik.builder.io/docs/advanced/routing/#custom-404-page)). You should be able to get away with some bare bones javascript in that file that checks secure cookies for something like 'Username' or 'User' info. Just an idea. That way if they previously logged in and you store those cookies at the root url, they should show up on that page as well.
