### ISSUE TITLE
[📖] Qwik homepage showing light mode text color on dark mode

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#3914]
### Suggestion

I'm not sure where the front page code is for Qwik so I thought I'd point it out here at least.

https://gyazo.com/550af805d0e76e1e25bd60eac94b50e2

It's showing the light mode's color for a section on the Qwik Homepage.

My guess is the text color should probably be white here.

**Comment by zanettin** [comment]
Thanks for mentioning this @thejackshelton 🙏 
Unfortunately i don't have enough power to change that neither since this page is built on builder.io 😅 
@hamatoyogi @steve8708 @adamdbradley smb able to quickly adjust that? removing the `dark-mode` class on the wrapper would make it a bit more readable 😄 

![Bildschirmfoto_2023-04-26_um_23_17_14](https://user-images.githubusercontent.com/3241476/234705052-cbeaeaa1-1764-443e-a77b-bc5078560c31.png)

**Comment by zanettin** [comment]
thanks to the new design, this issue got obsolete 🎉
