### ISSUE TITLE
[🐞] use* methods in conditional statements and in libraries

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#3943]
### Which component is affected?

Qwik Runtime

### Describe the bug

Similar issue was opened [here](https://github.com/BuilderIO/qwik/issues/3850), but the solution doesn't fit with custom hooks.

I maintain a library where I provide several localization functions, such as:

```typescript
export function $translate(keys: string | string[], params?: any, ctx?: SpeakState, lang?: string): any {
  ctx = ctx ?? useSpeakContext();

  ...
}
```

Why the custom hook is in a conditional block? So the consumer can use the same function outside a `component$`, for example in _Inline components_ providing the original context::

```jsx
export const MyComponent = (props: { ctx: SpeakState }) => {
  return <h1>{$translate('home.title@@Qwik Speak', undefined, props.ctx)}</h1>;
};

export const Home = component$(() => {
  const ctx = useSpeakContext();

  return (
    <>
      <MyComponent ctx={ctx} />
    </>
  );
});
```

This solution worked until now and still works, but from v0.103 of the Qwik linter it would seem that it is no longer allowed:

` error  Calling use* methods in non-root component  qwik/use-method-usage`

So I wonder:

1. Why _use methods can not be called conditionally_?
2. If they can't be called conditionally, why do they work?
3. If this is not a linter bug, what alternative do I have to offer the same functionality of the localization functions without duplicating the functions themselves to work in different conditions?

Thanks!

### Reproduction

https://github.com/robisim74/qwik-speak/blob/main/packages/qwik-speak/src/translate.ts

### System Info

```shell
Not relevant
```

### Additional Information

As a temporary solution, I turned off the linter rule in the library:

`'qwik/use-method-usage': 'off'`

**Comment by manucorporat** [comment]
The problem is that the eslint rule is doing the job correctly, you can not have use methods under conditions, all use methods need to run.

Same rule applies to react.

**Comment by robisim74** [comment]
As maintainer of a public library, I just want to know if I can continue to keep it like this, disabling the linter rule in the library, or if it might happen that it doesn't work in the next versions of Qwik: at the moment, the inconsistency remains between the behavior (it works) and the linter

**Comment by robisim74** [comment]
@manucorporat Even if I remove the condition:

```typescript
export function $translate(keys: string | string[], params?: any, ctx?: SpeakState, lang?: string): any {
  ctx = useSpeakContext();

  ...
}
```

I get the same error from the linter when I build the library: `Calling use* methods in non-root component`. It can't seem to detect that it's inside a library that offers an API: it expects to be called inside a component (which of course isn't there, it is in the app consuming the API).

**Comment by cmbartschat** [comment]
A function that calls `useSpeakContext` has to also start with the word `use`, because calling a hook can only be from a hook/component. We can't call hooks conditionally because the order the hooks are called needs to be the same every time the function runs.

I made a little [playground](https://qwik.builder.io/playground/#version=0.105.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTVDbiUyMCUyMGNvbXBvbmVudCUyNCUyQyU1Q24lMjAlMjBjcmVhdGVDb250ZXh0SWQlMkMlNUNuJTIwJTIwdXNlQ29udGV4dCUyQyU1Q24lMjAlMjB1c2VDb250ZXh0UHJvdmlkZXIlMkMlNUNuJTIwJTIwU2xvdCUyQyU1Q24lMjAlMjB1c2VTaWduYWwlMkMlNUNuJTdEJTIwZnJvbSUyMCU1QyUyMiU0MGJ1aWxkZXIuaW8lMkZxd2lrJTVDJTIyJTNCJTVDbiU1Q250eXBlJTIwVHJhbnNsYXRpb25Db250ZXh0JTIwJTNEJTIwJTdCJTIwc2hvdWxkVXBwZXIlM0ElMjBib29sZWFuJTIwJTdEJTNCJTVDbiU1Q25jb25zdCUyMHRyYW5zbGF0aW9uSWQlMjAlM0QlMjBjcmVhdGVDb250ZXh0SWQlM0NUcmFuc2xhdGlvbkNvbnRleHQlM0UoJTVDJTIydHJhbnNsYXRpb24lNUMlMjIpJTNCJTVDbiU1Q25jb25zdCUyMHVzZVRyYW5zbGF0ZSUyMCUzRCUyMChjdHhPdmVycmlkZSUzRiUzQSUyMFRyYW5zbGF0aW9uQ29udGV4dCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBjdHglMjAlM0QlMjB1c2VDb250ZXh0KHRyYW5zbGF0aW9uSWQlMkMlMjAlN0IlMjBzaG91bGRVcHBlciUzQSUyMGZhbHNlJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwKHRleHQlM0ElMjBzdHJpbmcpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKChjdHhPdmVycmlkZSUyMCUzRiUzRiUyMGN0eCkuc2hvdWxkVXBwZXIpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHRleHQudG9VcHBlckNhc2UoKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlMjBlbHNlJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMHRleHQlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCUzQiU1Q24lN0QlM0IlNUNuJTVDbmNvbnN0JTIwVHJhbnNsYXRlZENvbnRlbnQlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjB0cmFuc2xhdGUlMjAlM0QlMjB1c2VUcmFuc2xhdGUoKSUzQiU1Q24lMjAlMjBjb25zdCUyMHRvZ2dsZSUyMCUzRCUyMHVzZVNpZ25hbChmYWxzZSklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0UlN0J0cmFuc2xhdGUoJTVDJTIyRXhhbXBsZSUyMHBhcmFncmFwaCU1QyUyMiklN0QlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2xhYmVsJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTIwdHlwZSUzRCU1QyUyMmNoZWNrYm94JTVDJTIyJTIwYmluZCUzQWNoZWNrZWQlM0QlN0J0b2dnbGUlN0QlMjAlMkYlM0UlMjBUb2dnbGUlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGbGFiZWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCdG9nZ2xlLnZhbHVlJTIwJTI2JTI2JTIwJTNDcCUzRSU3QnRyYW5zbGF0ZSgnQ29uZGl0aW9uYWwlMjBwYXJhZ3JhcGguJyklN0QlM0MlMkZwJTNFJTdEJTVDbiU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QpJTNCJTVDbiU1Q25jb25zdCUyMFRyYW5zbGF0ZWRPdmVycmlkZUNvbnRlbnQlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjB0cmFuc2xhdGUlMjAlM0QlMjB1c2VUcmFuc2xhdGUoJTdCc2hvdWxkVXBwZXIlM0ElMjB0cnVlJTdEKSUzQiU1Q24lMjAlMjBjb25zdCUyMHRvZ2dsZSUyMCUzRCUyMHVzZVNpZ25hbChmYWxzZSklM0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDcCUzRSU3QnRyYW5zbGF0ZSglNUMlMjJFeGFtcGxlJTIwcGFyYWdyYXBoJTVDJTIyKSU3RCUzQyUyRnAlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDbGFiZWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDaW5wdXQlMjB0eXBlJTNEJTVDJTIyY2hlY2tib3glNUMlMjIlMjBiaW5kJTNBY2hlY2tlZCUzRCU3QnRvZ2dsZSU3RCUyMCUyRiUzRSUyMFRvZ2dsZSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZsYWJlbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0J0b2dnbGUudmFsdWUlMjAlMjYlMjYlMjAlM0NwJTNFJTdCdHJhbnNsYXRlKCdDb25kaXRpb25hbCUyMHBhcmFncmFwaC4nKSU3RCUzQyUyRnAlM0UlN0QlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiU1Q24lNUNuY29uc3QlMjBUcmFuc2xhdGVQcm92aWRlciUyMCUzRCUyMGNvbXBvbmVudCUyNCgocHJvcHMlM0ElMjAlN0IlMjBjdHglM0ElMjBUcmFuc2xhdGlvbkNvbnRleHQlMjAlN0QpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHVzZUNvbnRleHRQcm92aWRlcih0cmFuc2xhdGlvbklkJTJDJTIwcHJvcHMuY3R4KSUzQiU1Q24lMjAlMjByZXR1cm4lMjAlM0NTbG90JTIwJTJGJTNFJTNCJTVDbiU3RCklM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzaG91bGRVcHBlciUyMCUzRCUyMHVzZVNpZ25hbCh0cnVlKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTNDaDIlM0VOb3JtYWwlM0MlMkZoMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NUcmFuc2xhdGVkQ29udGVudCUyMCUyRiUzRSU1Q24lNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaDIlM0VPdmVycmlkaW5nJTIwQ29udGV4dCUzQyUyRmgyJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1RyYW5zbGF0ZWRPdmVycmlkZUNvbnRlbnQlMkYlM0UlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2gyJTNFRHluYW1pYyUyMENvbnRleHQlMjB3aXRoJTIwUHJvdmlkZXIlM0MlMkZoMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NsYWJlbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NpbnB1dCUyMHR5cGUlM0QlNUMlMjJjaGVja2JveCU1QyUyMiUyMGJpbmQlM0FjaGVja2VkJTNEJTdCc2hvdWxkVXBwZXIlN0QlMjAlMkYlM0UlMjBNYWtlJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJlbG93JTIwdXBwZXIlMjBjYXNlJTIwKFRvZ2dsaW5nJTIwdGhpcyUyMGRvZXNuJ3QlMjB3b3JrJTIwYmVjYXVzZSUyMG9mJTdCJTVDJTIyJTIwJTVDJTIyJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ2ElMjBocmVmJTNEJTVDJTIyaHR0cHMlM0ElMkYlMkZnaXRodWIuY29tJTJGQnVpbGRlcklPJTJGcXdpayUyRmlzc3VlcyUyRjM4MzElNUMlMjIlM0V0aGlzJTIwaXNzdWUlM0MlMkZhJTNFJTIwSSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aGluayklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGbGFiZWwlM0UlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1RyYW5zbGF0ZVByb3ZpZGVyJTIwY3R4JTNEJTdCJTdCJTIwc2hvdWxkVXBwZXIlM0ElMjBzaG91bGRVcHBlci52YWx1ZSUyMCU3RCU3RCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NUcmFuc2xhdGVkQ29udGVudCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZUcmFuc2xhdGVQcm92aWRlciUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QpJTNCJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwdHlwZSUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE) that shows a slightly different approach that follows the rules.

**Comment by robisim74** [comment]
@cmbartschat Thanks for your reproduction! You are right, renaming the function starting with `use*` would solve the compile problem: the problem is that this is a React convention, and until now the Qwik linter didn't report it (and we are close to version 1).

The other problem (passing the context to an _Inline Component_ and from there to the same translation function conditionally) doesn't seem to be solved anyway.

I have to think about it.
