### ISSUE TITLE
[📖] Google does not properly index the docs

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#4103]
### Suggestion

Trying to find documentation on `useVisibleTask$` yields nothing:
https://www.google.com/search?q=qwik+%22usevisibletask%24%22

It should be finding https://qwik.builder.io/docs/components/tasks/#usevisibletask but doesn't

**Comment by adamdbradley** [comment]
Just checked with Google's URL inspection tool, and it does look like `https://qwik.builder.io/docs/components/tasks/` is indexed. However, with the hash it says it's not indexed, and I'm not sure the fix for this. After a quick search I found [this](https://getdigitalresults.com/search-engine-optimizations/does-google-ignore-urls-with-hashtags/#:~:text=Google%20Doesn't%20Normally%20Index,on%20Google%20Search%20Central's%20%23AskGooglebot.&text=Does%20Google%20ignore%20hashtags%20in%20a%20URL%3F&text=Your%20browser%20can't%20play%20this%20video.) "Google Doesn’t Normally Index Hashtags in a URL".

I'm not sure what the right answer is, but we can keep researching and hopefully someone can point us in the right direction. I'll close this issue for now. Thanks
