### ISSUE TITLE
[DOCS]: explain "Only primitive and object literals can be serialized."

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#417]
Improve the description when you receive the error "Only primitive and object literals can be serialized." to explain a solution and point to a docs page with an example.

**Comment by manucorporat** [comment]
Error got improved!

**Comment by stefann01** [comment]
Maybe someone can post how to fix it also here, or at least a refference

**Comment by redsuperbat** [comment]
How is this issue completed? There is no solution or link to any documentation?

**Comment by redsuperbat** [comment]
I can leave a quick explanation of my use case:
I used axios to send a http request and tried to send the entire response through the `useResource$` hook. However since the axios response body is complex and sometimes circularly references itself qwick cannot serialize the response object and therefore crashes into oblivion.

Here was the code before the fix (simplified for readability): 

```ts
const getData = () => axios.get("/some/data/url")

export default component$(() => {
  const response = useResource$(getData);
  return (
    <>
      <h1 class="text-2xl">Title</h1>
      <Resource
        onPending={() => <div>Loading...</div>}
        value={response}
        // Accessing .data here
        onResolved={(res) => <div>{JSON.stringify(res.data)}</div>}
      ></Resource>
    </>
  );
});
```

My solution was to not send the entire response object through the `useResource$` hook but instead send only the body:

```ts
// Accessing .data here instead
const getData = () => axios.get("/some/data/url").then(it => it.data);


export default component$(() => {
  const response = useResource$(getData);
  return (
    <>
      <h1 class="text-2xl">Title</h1>
      <Resource
        onPending={() => <div>Loading...</div>}
        value={response}
        onResolved={(res) => <div>{JSON.stringify(res)}</div>}
      ></Resource>
    </>
  );
});
```
 
Hope this might help someone in the future 🚀
