### ISSUE TITLE
[🐞] strange behaviour: Code(3): Only primitive and object literals can be serialized

### ISSUE THREAD

**Issue by primozs** [BuilderIO/qwik#4371]
### Which component is affected?

Qwik Runtime

### Describe the bug

Expecting not to get an Code(3) Only primitive and object literals can be serialized error

I am attaching qwik-city route example file:
It contains one input field and form validation hook.
In the file there are 5 commented examples of different combinations when I get or don't get mentioned error.

Combinations are
- custom Input component
- translation function hook
- form validation hook,

### Reproduction

https://stackblitz.com/edit/qwik-starter-av68qb?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

comment example with no error and uncomment other examples 

### System Info

```shell
System:
    OS: Linux 5.14 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 21.47 GB / 31.09 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Chrome: 113.0.5672.126
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: ^5.22.1 => 5.22.1 
    vite: ^4.3.9 => 4.3.9
```

### Additional Information

*** Edit: new stackblitz with updated dependencies***
https://stackblitz.com/edit/qwik-starter-duqnd6?file=package.json,src%2Froutes%2Findex.tsx

**Comment by mishimalisa** [comment]
Additional concise reproduction: https://stackblitz.com/edit/qwik-starter-iwsagf?file=src%2Froutes%2Findex.tsx

**Comment by Oddadmix** [comment]
Hi @manucorporat, Any chance if you can please take a look at that issue?

**Comment by nynevi** [comment]
Tried a couple of things while debugging:
- removing `export` in `export const useFn =` here https://stackblitz.com/edit/qwik-starter-iwsagf?file=src%2Froutes%2Findex.tsx fixes the issue. I am guessing Optimizer thinks that this is an exported variable
- wrapping with `noSerialize` in `const fn = noSerialize(useFn());` in the same example, also works
- exporting an object literal like the following works:
```js
export const utilities = {
  useFn: () => (name: string) => name,
}

// reuse as
const fn = utilities.test()
```

I have a PR incoming, that skips serialization for exported functions that return another function

**Comment by robisim74** [comment]
@mhevery, please, is it possible to have an official explanation of this issue? Is this a bug? 

- If it's a bug, is a fix possible?
- If it's not a bug, what are we doing wrong with using functions that return functions directly in props? and why is the error raised only in some unpredictable cases?

It looks like the _Optimizer_ is trying to serialize the function (when in reality we are passing the result of the function as props, and it shouldn't be necessary). Furthermore, if you look at the compiled code, you see that it is wrapped in a Signal as Immutable, as I analyzed in this other issue: https://github.com/BuilderIO/qwik/issues/4038

Thanks!

**Comment by mhevery** [comment]
The issue is `useTranslate` this:
```typescript
export const useTranslate = () => {
  const t = (msg: string) => {
    return msg;
  };
  return t;
};

export default component$(() => {
  const t = useTranslate();
  return <div>{t('Enter your email')}</div>;
});
```

The problem is that `useTraslate` returns a naked function `t`. Under some circumstances, the system needs to serialize `t` and it can't because it is a naked function. (Yes the error could be better..)

```typescript
     <input
        name="email"
        type="email"
        value={v.form.data.email}
        onInput$={v.change$}
        onChange$={v.touch$}
        autoComplete="email"
        placeholder={t('Enter your email')}
        required
      />
```

In the above case `t` does not need to be serialized, as it `<input>` is part of the component which creates the function in the first place. 


```typescript
      <Input
        name="email"
        type="email"
        value={v.form.data.email}
        onInput$={v.change$}
        onBlur$={v.touch$}
        autoComplete="email"
        placeholder={t('Enter your email')}
        required
      />
```

In the above case, `<Input>` is a component. This means that `<Input>` can wake up independently from the parent component. If `<Input>` wakes up, it needs to be able to know its props.

So why do you need to know the `t` in that case (why not just the value of `t`). Well because at compile, it is not possible to know if the input is value (as in this case) or a signal. Therefore system serializes it just in case it is a signal.. serialization fails because `t` is not wrapped in `$()`.

Workaround:

```typescript
export default component$(() => {
  const t = useTranslate();
  // ...
  const placeholder = t('Enter your email'); // read value here, outside the JSX.
  return (
    <div>
      {(() => {debugger;})()}
      <Input
        name="email"
        type="email"
        value={v.form.data.email}
        onInput$={v.change$}
        onBlur$={v.touch$}
        autoComplete="email"
        placeholder={placeholder} // <= now it's clear it is not a signal, so we serialize the value.
        required
      />
};
```

**Comment by robisim74** [comment]
@mhevery Thanks so much for your explanation! Personally I agree with your workaround, and it's what I've been suggesting to do in my library for a while now.

But custom hooks that return pure functions are widely used by developers (not just i18n libraries...).

So I wonder: couldn't we instruct the _Optimizer_ when it encounters a function in props (that is not a QRL) to make it say: "Hey, I don't know anything about you! So I'll treat you like a function that belongs to the global scope, and I'll put you in _mutable_ props!"

I don't know the _Optimizer_ well enough to modify it, but I tried to simulate what would happen if it were considered `mutable`. To do this I simply renamed the `use*` function to `make*` function:

https://stackblitz.com/edit/qwik-starter-6rtqhj?file=src%2Froutes%2Findex.tsx

Everything seems to work: both when the state of the parent component changes and when the state of the child component changes.

Looking at the compiled code, instead of:
```tsx
  const count = useSignal(0);
  const myFn = useFn();
  return /* @__PURE__ */ _jsxQ("div", null, null, [
    /* @__PURE__ */ _jsxC(MyComponent, {
      get val() {
        return myFn(count.value);
      },
      [_IMMUTABLE]: {
        val: _fnSignal((p0, p1) => p1(p0.value), [
          count,
          myFn
        ], "p1(p0.value)")
      }
    }, 3, "H1_1"),
```
we have:
```tsx
  const count = useSignal(0);
  const myFn = makeFn();
  return /* @__PURE__ */ _jsxQ("div", null, null, [
    /* @__PURE__ */ _jsxC(MyComponent, {
      val: myFn(count.value)
    }, 3, "H1_1"),
```

Would there be some downside or side effect that I am unable to see?

Thanks again.

**Comment by mhevery** [comment]
> So I wonder: couldn't we instruct the _Optimizer_ when it encounters a function in props (that is not a QRL) to make it say: "Hey, I don't know anything about you! So I'll treat you like a function that belongs to the global scope, and I'll put you in _mutable_ props!"

That would be a very surprising behavior and would cause issues.

Why not just have the function be global to begin with? then it should just work...

**Comment by primozs** [comment]
Hi, Yes the workaround was known and also already forgotten since the opening of this issue. Maybe sooner since I did not list it. This was the reason it was not acceptable to me. It is something you must know. But ok.
