### ISSUE TITLE
[🐞] Destructuring and aliasing prop with default value lost reactive

### ISSUE THREAD

**Issue by utherpally** [BuilderIO/qwik#4378]
### Which component is affected?

Qwik Runtime

### Describe the bug

```tsx
export const Child = component$<{ count: number; foo?: number }>(
  ({
    count,
    foo: bar = 2, // Remove default value, everything work again
  }) => {
    // this hook run only once
    useVisibleTask$(({ track }) => {
      console.log("Double count:", track(() => count) * 2);
    });
    return <p> Count: {count}</p>;
  }
);

```

### Reproduction

https://t.ly/nPbG

### System Info

```shell
Qwik Playground
```

**Comment by manucorporat** [comment]
Realize that the act of access the property is what causes the subscription:
```
track(() => count)
```
was working because of an optimization that is helping in this case, but please dont rely on it. Avoid destructuring of props when u can.

However, I see that in this particular case the optimizer could still optimize. But don't rely on it, planning to add a new eslint rule to warning about things like: `track(() => identifier)`
