### ISSUE TITLE
[🐞]

### ISSUE THREAD

**Issue by keshavuchiha** [BuilderIO/qwik#4443]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am trying to build a login system with login modal. Having state declared using qwik context. But it is not updating the modal to be hidden when clicked on close button

### Reproduction

https://stackblitz.com/edit/qwik-starter-8sxkdy?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Flayout.tsx,src%2Fcomponents%2FTemp.tsx

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 1021.59 MB / 7.59 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
  Browsers:
    Firefox: 113.0.2
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

**Comment by OrenSayag** [comment]
I'm 0 experienced in Qwik, so I'm not sure if this is helpful:

I asked the cahtbot of Quik's site (https://qwik.builder.io/docs/components/slots/#slots) the following:

"can slot be affected from context from layout?"

And the answer was:

`
In Qwik, slots are declarative and cannot be affected by context from layout. This is because Qwik needs to be able to render parent and children components independently from each other.
`

**Comment by gioboa** [comment]
Please have a look at the official docs. [Here](https://qwik.builder.io/docs/cookbook/portal/) you can find a Modal example.
