### ISSUE TITLE
[✨] Built-in Portal Support

### ISSUE THREAD

**Issue by FlatMapIO** [BuilderIO/qwik#4575]
### Is your feature request related to a problem?

There doesn't seem to be a good way to implement Portal functionality right now.  Applications can overcome this, but it may be difficult when creating an a11y-friendly component library with complex Overlay behavior

### Describe the solution you'd like

Providing `<Portal />` components or other qwikized ways

### Describe alternatives you've considered

No

**Comment by manucorporat** [comment]
Looking for a good use case for this functionality, wonder if this UI can be built easier today with Dialog or the new popover API!

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
https://developer.chrome.com/blog/introducing-popover-api/

**Comment by FlatMapIO** [comment]
[daisyui](http://daisyui.com/) uses the dialog element to implement Modals

Advanced component libraries like radix-ui and ark-ui implement it themselves and rely on Portal. Assuming ark-ui will add a qwik version in the future, Portal can provide a lot of help.

a11y-dialog summarizes [some of the problems with the native dialog](https://a11y-dialog.netlify.app/further-reading/dialog-element). However, "Clicking the backdrop does not close the dialog on Chrome" mentioned in it is not a problem in daisyui.

The current support for the `popover` element may not be widely adopted within three years.

**Comment by GrandSchtroumpf** [comment]
We had a bunch of discussion about using the `<dialog>` element on Qwik UI. For me the two issues with the `<dialog>` element  are :
- ::backdrop cannot be animated.
- you cannot set `role="alertdialog"` on the dialog element.
Everything else can be easily fixed with a little bit of JS (that you would have to do anyway if you re-implement everything).

**Comment by thejackshelton** [comment]
@GrandSchtroumpf yeah I saw this issue in Adam Argyle's dialog post. Hopefully they add animations to ::backdrop in the future. Why is there an issue with setting a role on it?

@manucorporat If we were to have a built-in portal, I looked into Solid's implementation and it seems like it might be the easier to "convert" a similar implementation to Qwik due to the Solid having signals and JSX along with a similar "React-like" API. 

I think the challenging part would be learning about other solid primitives, and it might be easier to build one from scratch in Qwik I'm not sure. 

I think if this were implemented it would be a PR to Qwik core and not Qwik UI, since I can assume not everyone would want to use the Qwik UI library and have their own custom portal implementations.

Here's the Portal component in solid along with their vitest tests for it.
https://github.com/solidjs/solid/blob/main/packages/solid/web/src/index.ts
https://github.com/solidjs/solid/blob/main/packages/solid/web/test/portal.spec.tsx

**Comment by jessezhang91** [comment]
Given dialog's support is ~92% (via caniuse) and popover's support being ~38%, my team didn't feel comfortable using native browser support for these portal cases.

We ended up implementing something portal-like by encapsulating the portal content in `QRL<() => JSXNode>` functions that we passed to portal slots and rendered them using `<RenderOnce children={fn()} />`. We had to hack around serialization (via `noSerialize`) but since we were only doing this for dialog/popovers which required user interaction first anyway, this was always going to be client-side-only.

With that said, we would love to see built-in portal support so that (1) we have confidence in the maintainability of whatever we build versus the hacky solution that may end up breaking in a subsequent version of Qwik, (2) rendering of portals may be optimized to be made more efficient/etc., and (3) potentially have portals functioning in server-side contexts as well (e.g. render a modal pre-opened as part of SSR).

**Comment by joshdchang** [comment]
What I've been doing that seems to work well and plays nicely with Qwik (I don't feel like I'm breaking any rules or best practices) is using context, signals, resources, and QRLs all in conjunction with each other, although I do agree that having a common use case like a modal require a deep understanding of the framework is probably something that could be improved.

In the layout, I create a context for the portal content:

```tsx
import {
  Resource,
  Slot,
  createContextId,
  useContextProvider,
  useSignal,
  useResource$,
  component$,
  type QRL,
  type Signal,
  type JSXNode,
} from "@builder.io/qwik";

export const PortalContext = createContextId<Signal<QRL<JSXNode> | undefined>>("portal");

export default component$(() => {

  const portal = useSignal<QRL<JSXNode>>();
  useContextProvider(PortalContext, portal);

  const portalResource = useResource$(({ track }) => {
    track(() => portal.value);
    return portal.value?.resolve();
  });

  return (
    <>
      <Slot />
      <Resource
        value={portalResource.value}
        onResolved={(portalNode) => <>{portalNode}</>}
      />
    </>
  );
});
```

Then, when I wish to use the portal, I can create a component for the portal content and pass that to the portal context:
```tsx
import {
  component$,
  useContext,
  $,
  useOnDocument,
} from "@builder.io/qwik";

// body of the modal
export const Modal = component$(() => {

  const portal = useContext(PortalContext);

  // example of allowing `esc` to close modal
  useOnDocument(
    "keydown",
    $((event) => {
      if (event instanceof KeyboardEvent && event.key === "Escape") {
        portal.value = undefined;
      }
    })
  );

  return (
    <>
      <div>
        <button onClick$={() => (portal.value = undefined)}>
          Close modal
        </button>
      </div>
    </>
  );
});

export default component$(() => {

  const portal = useContext(PortalContext);

  return (
    <>
      <button
        onClick$={() => {
          portal.value = $(<Modal />);
        }}
      >
        Open modal
      </button>
    </>
  );
});
```

**Comment by hexa-it** [comment]
What's the status on this?

**Comment by brandonpittman** [comment]
Here's an example of why we need Portals:

https://codepen.io/uncle_tacitus/pen/WNYBggL

If you have sections that scroll and have popovers that can fall outside of the overflow container, that content will get cut off.

**Comment by wmertens** [comment]
I think people are confusing portals with popovers? A portal is for rendering elements in the current context but displaying them elsewhere. This is not possible in Qwik right now and I do wonder if it's needed.

@joshdchang's solution uses `$(<Foo />)` which converts that into a static QRL. This means, you can't put scope variables into it. Instead, you need to send a render function or simply a component.

Here's an example of a dialog using this principle, just missing some styling to make it a popover. You can do some more signaling to indicate when it's done, e.g. a function to call that returns a promise.

```tsx
import { component$, createContextId, useContext, useContextProvider, useStore, Component } from '@builder.io/qwik';

type Ctx<P extends object = any> = {
  show: boolean
  Cmp: Component<P>
  props?: P
}
const cId = createContextId<Ctx>('modal')

const useModalProvider = () => {
  const store = useStore<Ctx>({} as Ctx)
  useContextProvider(cId, store)
  return store
}

export const Modal = component$(() => {
  const ctx = useContext(cId)
  return ctx.show ? <div>
    <div>MODAL: <ctx.Cmp {...ctx.props} /></div>
    <button onClick$={()=>ctx.show = false}>close</button>
  </div> : null
})

export const Hello = component$<{name:string}>((p)=> <>Custom component saying "hello {p.name}"</>)

export default component$(() => {
  const ctx = useModalProvider()
  return <>
    <button onClick$={()=>{
      ctx.show = true; ctx.Cmp = Hello; ctx.props = {name: "there"}
    }}>Show modal</button>
    <Modal/>
  </>
});
```

[Playground link](https://qwik.builder.io/playground/#v=1.1.5&buildMode=production&f=7VbBToQwEL37FQ2XhYRw0JMVujF4dCOJX8C6mI3ZFSJrXEP6776ZKVCQ7N1ELpTSTmde38w8jzS31zdLpInnTIs9Ovrjnpo8xz06VmOhvUQ9ZkF%2BOqcF6gwScdeqevuGcgjI0KQMXoRZu6%2B%2FtNrW6OnlO77zY6PHE9KComJRstaqwGUJ9C%2BovNmvbMFpJlwd6115WEVXbin83tBMH8nkxpxYYTGTjTKEDXUWJY4iiLBwIVnhQyxbaYG7e%2F6Gm1OmsAPk8FL%2BuYhOZ%2FGgrw8w79nF74SgUmvF2k3unEabp4f7R61SWgHwVJckCY0ZNAuyiMiTDSLzRnXThVFmBtuZei0PbWUNOnBbDaIQW51Q1NyRUBdm8QmZ%2FfjSjnqVFoFoTRg2OAg5kX8CIbSTgUJt%2BU0SMtizia5JaJ8NQOfxkIvlawbf5K5DD0GXj8sQkCF6PCiox9%2FxBKGaSYwywdASfzlGFaD7f1SBZRvWmmcywCz0IcTR7BvnKWXrf3X9m9X1Bw)

**Comment by brandonpittman** [comment]
The problem that portals solve is when you need to render an element outside of its parent.  If you need to show a popover in a scrolling container and the element could get cut off, portals solve the issue.

**Comment by wmertens** [comment]
@brandonpittman I guess my example needs some more scaffolding. The idea is that you mount the Modal in your app root, so it's not part of your containers.

Did you try the playground?

**Comment by GrandSchtroumpf** [comment]
Wouldn't Portal break streaming? It feels like a feature that can only work on the browser, but maybe I'm mistaken.

**Comment by wmertens** [comment]
@GrandSchtroumpf The approach I show works fine with streaming, it doesn't matter. By putting the portal at the bottom of the root component, it's even likely that the modal will already render during SSR.

The only difference with react portals is that the Hello component would be rendered in the context of the caller, not the context of the modal. I'm not convinced it's needed.

**Comment by brandonpittman** [comment]
@wmertens Just checked the playground. When I add overflow styles, it breaks.

Here's an example: https://qwik.builder.io/playground/#v=1.1.5&buildMode=production&f=7VZNa4NAEL33VywLJQZE7KEUrBqKPTY0kF%2BgzWcxXYlpmyD73%2FtmVt1NKrkXmkvixp2dffPmzXNJEz7093FZ419SzXf46P7uuMlrPKR9YZX2GveYBtnhGM8gNOjERS1U8Q49BGaYUim%2BCLR6o74jUSgM9fwDz9muiuwJ8Yyuxa5kEokZqmWwf4P0Jr%2FaBael3minFnk5Gt%2B0ryLvKa10NzkrWetW2M0k1odwoEZD4%2BgGY7w40K3IwTdb6YW2%2BPyMNM%2BpwglQwkMN2N7ocDQZdAKB8E5c%2FB0QVGIiyLwBN%2BNpmkrVW2J9JGReYKpAkyR6UAFFeReGt1LrliHk9aavz08vkYgpHJAWTRAE9JsR1qCWsYRmgzGF1gs13jhJ%2B0QSscrLeqlTzOt62VtIbG1tZcTzCypyAYahvgtG3NBki4yd1KnnVTgIHZR9Ak4Mn55vdX4iwyk3HKKpAtqnJchvD7kqdhdYnxHDc%2BBmjDuIrRXJVKn2ALbcrjeH9T4%2FAeqCvMQc8wHr92F1xJJTE0x4DJovqomC0q3gLKhS8By2MIM4U7b0cfAm2%2FHIC1S6xABpFrh%2B1FEMpJAwJPul1BwD58wpAPeFWycczQCwdLSF%2F9f8v6n5Pw

**Comment by brandonpittman** [comment]
Right. This doesn’t take dynamic content from the caller.

**Comment by wmertens** [comment]
@brandonpittman not sure what you mean, the Hello component and its props are passed dynamically. You could also pass a render function.

**Comment by brandonpittman** [comment]
@wmertens I see it now. It’s not using slots. It reminds me of the old Vue portal package from before Vue had real portals.

If you wanted to have multiple portals be used at once, you’d have to set them up in advance in the root, right?

**Comment by wmertens** [comment]
@brandonpittman not really, anything can be done in the single Modal component but it needs to be set up for it of course.

For example, you could have an array of modals to display, and useModal could return functions to show/hide/await them. The modal component would iterate through the array and render all of them and put the backdrop behind the most recent one.

I'm guessing you'd like something like
```tsx
<Portal to={modalPortal}>
  <MyCmp/>
</Portal>
```
?

That's not possible with Qwik, because you can't access your children while using context. Maybe something can be done with a portaling Slot component, but instead you could just pass rendered children. Remember, their context will be the modal context, not the component context.

`ctx.rendered = <MyCmp>...</MyCmp>`

[Here's a better playground](https://qwik.builder.io/playground/#v=1.1.5&buildMode=production&f=5VhNa9wwEL3nVwgdwiZdyzRLQ9nabmkg0EMg0GPJwet1sk79he00WYz%2Fe99oZMneLIVCoIceQmx5pBnNvHl62iloPl461MDAIWBJb3O40ZBD5fxtxKgZ1cc1PVvWpZfrJn6gHliemALKw4JLJFHj46p7CW7BQGjRbSuqzSOIEsnE8RXhH4Xa7qrntdhUOO3j8hO5KurPa%2BcwuAVEBSsWjN%2FSCxc73eIdK%2BlkcK0SUHX4qr0QRLSQRbWNc4nUselXLYVgXVNdA1ZGoldK1QMLo7D%2FITddKZeiVnrgbkBRsDNeAOm5oSXHlM0wYuSRlk%2BhEz46kt7s%2BT7OQf4DGJbShMCOFWKBLS15IW1hwKcH9MYPwKoz862EhCHH8DXmSgxIKtxQhARd0oZmnzIG4XYy6kfbgRXjCTzOVtf7pQQfIxhTge6FNzwSIOKfBm66xjlHkrkyS5qrKDXi9FTwoAdRVcq7wbbCJGg22FQvctI4u9X4%2BR7%2B8RUnP4Xh5Q8y4vA7iAl032o66yJysuKdUcewuZjYHEkXxQu0UrjB%2BEwAome9BuFlzOXUmalPQsIEOT9w1fvnEKb5XjxXzc%2BWBQpWFZs0iZFYYrSswEHViCJtW5yy2kI7FOf%2B4DzNwGACo5Asr0wCC0w%2FmC0C917dZEXc7KVTyT1Xe2ELFTKIz2yBAIO8alPrgVcducv4I%2FrC3xxbzJRTbAVQ8lBC6%2FH%2BMUQL3asavdHVE3oAisXWrY33ZCV3eqG%2BVjR5UJIo8%2ByVu5s9cezbQlk%2BNNlW7LwWBAShWOcQ756WbF4CD2ljkWqyPUmazXqckK0ovFjaz4cFoBjtVFcL0qsU3%2FQTYTLk5B5%2BYsSAhU2aJeRtk6IPabNrUGJ0XVU4fCIBmplPtaQSTsyc0TCC0MHiO4WoW%2FavsPFHSXPIwIsj1bEZ54I78DMZmHd3rP6HWmh1eflvtRAs9JVb%2F4Ygx5tmsi3VY4ubSvarUWXa%2BWVd%2BNs4a%2FdP2ZeV%2BqDeAzNt59%2Fj9qRwlZF0zQolX8x2adpJXZZQEpx9bWCrD49o0qwGazTJ3CVuQ%2FkzVD0mKKBORoHPpm%2Bo3H4D)

**Comment by brandonpittman** [comment]
@wmertens Thanks. It’s not the API I’m used to, but I see how it could work.

**Comment by wmertens** [comment]
@brandonpittman actually, I can do more than I expected. [Here](https://qwik.builder.io/playground/#v=1.1.5&buildMode=production&f=5Vjfa9swEH7fX2HEGEnX2CyhhWWJNygM9lAY7HHswXGc2q1jG9ttE4z%2F9313kizJyQqFwR5mKEXSSbof3326iwWa%2Bfzq4xApCBgEXNLIhRtNGVS6I41RNStfbhpwtAfuHWaMAG5S4RTj8Au4VO5vD6vv4CMk7Lbxys09aBOuxWMW4h8pTs%2F0Up26ovlPmMTLWiy9SbUkSQ7DU5ltaQVvSJNgyZqEY2TcYtD2%2BiTVoEI4EftyG%2BUCblSyMPWWprT5TrzVce1B6ai1HPwzmZIDelAlWch6tQeftMaOt5NKHyTnabMPBsLbsvYqkqYElGtsD28y15%2FZtYvyJjE7z1AMjL%2BkfbyuAIshu2cEb06cbwWKHjp6ohMdlUZvHE5gp2pSloxrEYGiWxF2WraXNeYb3Oeczl6lMJyjJNuxFmVCd1ttlWfm8u6nih9baHvm3TtPLs3I%2BeJXP6SQpboU2JQHYSVcutDLO2iBVVQMpMwsvxOhNKJFEYKsXdi75qEpR96rqhoyc0vm1GnDmud1rgGf%2FZt9RVZIm4czXCkW6nzfH03z9b3hDfqmvdFERshWXkU9pgIJkRyp3gUX1klplO9mKRXNbYkq9SFB3fEEhOvNCjbUKDyX9YO1syzyI881stiC5t4miSOEnNg52%2BPRrb190jSoGFiCLRlOuAgsIxy4njrBMt%2BxdyU7Hx2JTVt4%2BJtVdbaP6qMwjQBHhNNwAI%2BiGcPGsolSfKwuIUomPnHQL9nfRv8K3Qmqu6XuqfpQ0gPnV3jziFYGVdiAqSY6kpRI%2BaCu8mlz7wt6BqYn190e6d14Mdk6JlMkDhNN%2F7rEE3d1tvXSWQNSRcCrHM3JjEvSWYzbknrAtnK35UDH7VFM8mJYNt5nfW3sQNuJZEH9Af1L6VliXfOpnlY7WKBYrxPh9a6UJiw8Gs48dM7si%2BX3NSriI2L1uNtJBC9PRP6ArEPjgGoEKPOByUsVDdL39HgHbvb8SF1%2Bg%2FTXT4eBzh0j%2FSNF28Ms%2BCpIv1hdjh%2FQyRkgDeCQODWJKvlVjU2F8x%2BWpYvr639blkKCf%2F3gn3OEbvrjbeHfN2gas6faL5I2KKp9sI2y5viYfVn4V%2F4HYKZpgx0aWR9dpaCOdy1kj5wmSSs4LGtBNBOwgPVKrcAnWQWyq2P3SjSm%2BTMaLGzwgToRrgIp%2BheL6N8) I'm embedding the close callback.

The trick is to create the context like so:

```tsx
const useModalProvider = () => {
  const ctx = {
    data: useSignal(),
  } as Ctx;
  ctx.open = $(p => {
    ctx.data.value = p;
  });
  ctx.close = $(() => {
    ctx.data.value = false;
  });
  useContextProvider(cId, ctx);
  return ctx;
};
```

only ctx.data is reactive, but open and close get serialized and refer to the context

**Comment by wmertens** [comment]
But indeed, when I try grabbing context from the components I'm rendering in the modal they break.

Actually, I haven't used React portals since I made my own dialog using the above technique before portals came out.

However, looking at [the docs](https://react.dev/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal), I wonder if they couldn't be used for a more efficient qwikify$?

one react root rendering all qwikify$ components as portals, and then vice versa being able to embed Qwik into the React DOM.

**Comment by mhevery** [comment]
Do you think https://github.com/BuilderIO/qwik/pull/4928 is sufficient to close this issue?

**Comment by wmertens** [comment]
@mhevery I see you forego the event approach after all, but in any case the example looks great!

What are your thoughts on providing a JsxNode as well, like I show in my most recent sandbox?

What is missing from the cookbook though is a mention that the context the components will render under is the popup provider's context, so when using this technique, users have to be aware of this.

**Comment by thejackshelton** [comment]
I went over misko's additions to the docs with the modal cookbook, and I am struggling a bit to think about how Portals (or currently called popups) would work as a primitive in Qwik UI. 

Portals are used in both modal and non-modal components. A good example would be to check the DOM in Radix's examples here. The portal content is a direct child of the `body` tag, outside of its parent.

https://www.radix-ui.com/primitives/docs/components/dialog
https://www.radix-ui.com/primitives/docs/components/popover

The most basic use case for them is when a parent has an `overflow: hidden` or `z-index` style, but you need to visually "break out" of its container. For example, global UI such as a listbox, modal or a tooltip. 

For some components in Qwik UI, we would like the consumer to choose whether their component is modal or non-modal. Such as preventing scroll and keeping the focus locked inside the popup container (modal), or being able to interact with the rest of the page, but also with portal content like a popover (non-modal). 

This is consistent with other headless UI libraries. Take for example a Combobox component from Solid's Kobalte library:
https://kobalte.dev/docs/core/components/combobox

Portals are used in many primitives, and each component implementation usually contains a `<Portal />` component somewhere in the API, and have props such as `modal` or `preventScroll`.

Their API is something like this:

```tsx
<Combobox>
  <ComboboxLabel />
  <ComboboxControl>
    <ComboboxInput />
    <ComboboxTrigger>
  </ComboboxControl>

  <ComboboxPortal> <--- portal here
    <ComboboxListbox>
      <ComboboxOption />
    </ComboboxListbox>
  </ComboboxPortal>
</Combobox>
```

> In other frameworks, this is often solved by a dedicated API such as createPortal(). 
> However such API's don't work well with server-side rendering, and so an alternative approach is needed.

Would the **popup** or `popupManager` here be considered as a "replacement" to portals? And if so, would it be possible to render that content outside of its parent and adjacent to the body tag for non-modals as well?

reference: https://qwik.builder.io/docs/cookbook/modal/

Also, after reading through this GitHub issue again related to portals, wout mentioned something that I have some questions about:

> What is missing from the cookbook though is a mention that the context the components will render under is the popup provider's context, so when using this technique, users have to be aware of this.

reference: https://github.com/BuilderIO/qwik/issues/4575#issuecomment-1675829239

As a library author, does this mean it would be more difficult to:
- use state management with context between portal/popup content and their parents? 
- abstract away the popup manager to consumers?

If you guys also have any ideas for how to expose this as an API for headless would love to hear it. I started a portal implementation for Qwik UI today, and came across a decent bit of confusion regarding this. I'll be looking at this again tomorrow when I get time.

This is a long post, but if it means developers using Qwik have a better experience it's worth it. Appreciate taking the time reading this guys.

cc @mhevery @wmertens

**Comment by mhevery** [comment]
> @mhevery I see you forego the event approach after all, but in any case the example looks great!

I think the event approach is more complicated and deserves itso own cookbook. 

Aspect:
1. How to do popup
2. How to know when a popup should happen

Those are two different things. The event solves the second problem.s

**Comment by mhevery** [comment]
@thejackshelton https://github.com/BuilderIO/qwik/issues/4575#issuecomment-1679936609

Yes, it is a long post so let me try to answer and let me know if I miss anything

## Adding content to `document`

So my idea is that in root `layout.tsx` you do this:

```html
<PopupManager> <-- Developer determines the location of the portal by placing this in correct location.
  <Slot>
</PopupManager>
```

This means that in effect:
```html
<HTML>
  <body> 
    <!--PopupManager-->
       <Slot/> <-- where the rest of the application goes.
       <!--Place where Popups will be inserted.-->
    <!--/PopupManager-->    
  </body>
 </HTML>
```

Perhaps the cookbook could be clear on that, PR to fix up the wording would be great!





> For some components in Qwik UI, we would like the consumer to choose whether their component is modal or non-modal. Such as preventing scroll and keeping the focus locked inside the popup container (modal), or being able to interact with the rest of the page, but also with portal content like a popover (non-modal).

What does that mean in terms of popup manager? Does it mean you have to insert it into different location?



> Would the **popup** or `popupManager` here be considered as a "replacement" to portals? And if so, would it be possible to render that content outside of its parent and adjacent to the direct children of the body tag for non-modals as well?

Correct, that is the idea. Can you suggest how we could make the cookbook more clear on this?

> As a library author, does this mean it would be more difficult to:
> 
> * use state management with context between portal/popup content and their parents?
> * abstract away the popup manager to consumers?

I was hoping that the [cookbook example](https://qwik.builder.io/docs/cookbook/modal/) would make that clear. 
- when opening up a new modal, you do it at the location of `PopupManager`. 
- You can pass any state to the component, which will be open by the `PopupManager` so there should not be any issue with state managment.

**Comment by wmertens** [comment]
I wonder what happens to the context if you use a render function. The QRL should store the lexical state, so everything should just be fine?

E.g `<Popup show={signal.value} onShow$={()=><MyComp state={ctx}} />` where ctx is context from where it's defined

**Comment by mhevery** [comment]
> I wonder what happens to the context if you use a render function. The QRL should store the lexical state, so everything should just be fine?
> 
> E.g `<Popup show={signal.value} onShow$={()=><MyComp state={ctx}} />` where ctx is context from where it's defined

I like that idea. We should explore it to see if it works...

**Comment by thejackshelton** [comment]
Hey everyone! You can do modal / dialog portals now following the cookbook section of the docs.

If you're looking at implementing a popover portal, something similar to a dropdown, popover itself, etc. I would check out the discussion and implementation here:
https://discord.com/channels/842438759945601056/1138902270105366679/1143917159756611754
