### ISSUE TITLE
[🐞] Internal assert when SSR rendering <Link> inside a <div> container

### ISSUE THREAD

**Issue by omarbelkhodja** [BuilderIO/qwik#4618]
### Which component is affected?

Qwik Runtime

### Describe the bug

When rendering a `<Link>` element inside a `<div>` container, the following error occurs when clicking on the link :
`Error: Internal assert, this is likely caused by a bug in Qwik: close not found`

### Reproduction

https://stackblitz.com/edit/qwik-starter-jg6cng?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Open the devtools console
2. Click on the 'Flower App' link
3. Assert will trigger

### System Info

```shell
I'm on Windows and using Chrome
```

**Comment by manucorporat** [comment]
The issue is caused by:
```
    containerTagName: 'div',
```
in entry.ssr.tsx

it's making a `<div>` element as the root container then, rendering a `<head>` inside, this goes against the html spec and everything falls apart.

The error message indeed is not helpful and i will work to add another error that early detects this!

In the meantime, remove the `containerTagName: 'div',` config!
