### ISSUE TITLE
[🐞] Unit test with image imported as `jsx` failed

### ISSUE THREAD

**Issue by ahnpnl** [BuilderIO/qwik#4652]
### Which component is affected?

Qwik Runtime

### Describe the bug

I tested the new feature by importing an image as jsx but unit test threw error

<img width="875" alt="image" src="https://github.com/BuilderIO/qwik/assets/27772165/c7e88cd7-b671-44b8-b5c8-8597a762c899">

### Reproduction

https://github.com/ahnpnl/my-qwik-app/tree/bug/img-src

### Steps to reproduce

- Check out branch `bug/img-src`
- Install deps with `yarn`
- Run `yarn test.unit` and observe the error

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 45.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /opt/homebrew/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 114.0.2
    Safari: 16.5.1
```

**Comment by nsdonato** [comment]
I have checked and although there is no documentation on this, I have found this:

This happens because the image imported as jsx must be inside a media folder. Here is the image from the VSCode help. 
![image](https://github.com/BuilderIO/qwik/assets/7875216/f866422e-46a5-47e5-8d08-ca06f135dc50)

On the other hand, after adding this, the test runs correctly, although there are some strange logs, I attach another image.
![image](https://github.com/BuilderIO/qwik/assets/7875216/5059fd8e-b679-4921-8bc7-9d812c38a852)

@manucorporat my doubt is: to import an image as jsx, you always have to go through the optimisation (which creates the media folder automatically). Or could you use it as he is doing, manually creating the media folder? Keeping in mind that the image should always be in /public otherwise it gives an error.

The blog doesn't talk about that folder and I haven't found any documentation on the page about this new functionality, if you clarify it I'll add it. thanks!

**Comment by nsdonato** [comment]
Hey @ahnpnl I have checked and although there is no documentation on this, I have found this:

This happens because the image imported as jsx must be inside a media folder. Here is the image from the VSCode help. 

![image](https://github.com/BuilderIO/qwik/assets/7875216/f866422e-46a5-47e5-8d08-ca06f135dc50)


On the other hand, after adding this, the test runs correctly, although there are some strange logs, I attach another image.

![image](https://github.com/BuilderIO/qwik/assets/7875216/5059fd8e-b679-4921-8bc7-9d812c38a852)

@manucorporat my doubt is: to import an image as jsx, you always have to go through the optimisation (which creates the media folder automatically). Or could you use it as he is doing, manually creating the media folder? Keeping in mind that the image should always be in /public otherwise it gives an error.

The blog doesn't talk about that folder and I haven't found any documentation on the page about this new functionality, if you clarify it I'll add it. thanks!
