### ISSUE TITLE
[🐞] Production build step error with Modular Forms in Qwik v1.2.X

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#4789]
### Which component is affected?

Qwik Runtime

### Describe the bug

Since Qwik v1.2.X, an error occurs when running `pnpm preview` when using `formAction$` which is built on top of Qwik's `globalActionQrl`.

Issue with info at Modular Forms: https://github.com/fabian-hiller/modular-forms/issues/59#issuecomment-1623428177

<img width="726" alt="Screenshot 2023-07-13 at 13 55 51" src="https://github.com/BuilderIO/qwik/assets/35291865/a06390c8-e19f-4e28-9ece-75a95f63d7dd">
<img width="533" alt="Screenshot 2023-07-13 at 13 55 40" src="https://github.com/BuilderIO/qwik/assets/35291865/ff10ad41-5adc-4aec-b013-eac3f81c81e4">

### Reproduction

https://stackblitz.com/edit/modular-forms-qwik-actions

### Steps to reproduce

1. Clone project
2. Make sure that Qwik v1.1.5 is used
3. Run `pnpm preview`
4. Everything should work
5. Upgrade zu Qwik v1.2.X
6. Run `pnpm preview`
7. TypeError: Cannot read properties of undefined

### System Info

```shell
Not relevant
```

**Comment by manucorporat** [comment]
This is caused by a circular dependency in qwik-city, we will try so solve it, but in the meantime, make sure, this two imports are imported in the following order in `entry.preview.tsx`:
```
import qwikCityPlan from "@qwik-city-plan"; 
import render from "./entry.ssr";
```

https://github.com/BuilderIO/qwik/blob/b151cb4bbc667c52c1d32a5b93223c27feff9b5a/starters/apps/base/src/entry.preview.tsx#L14-L15

all starters already have them in the right order, it's unfortunate, but it will help prevent this issue.

**Comment by fabian-hiller** [comment]
Seems to work. Thank you @manucorporat!
