### ISSUE TITLE
[✨] Have private folders within src/routes/ directory

### ISSUE THREAD

**Issue by christinatka** [BuilderIO/qwik#4987]
### Is your feature request related to a problem?

It would be nice to have a way to separate our UI logic from the routing logic within `src/routes`. Private folders would allow us to have implementation details within our routing, but it ensures that it never gets treated as part of the routing. 

### Describe the solution you'd like

The implementation here can be similar to how Next.js handles private folders: https://nextjs.org/docs/app/building-your-application/routing/colocation#private-folders

> Private folders can be created by prefixing a folder with an underscore: `_folderName`

Anything within `_folderName` and all its subfolders get opted out of routing.

### Describe alternatives you've considered

Currently, we are keeping any UI logic files on the same level as the `index.tsx` for our route. We avoid using non-route-specific folders in order to not have any mishaps of creating an accidental `index.ts` file for exporting.  This is an alternative for us right now, but having a dedicated private folder would make things more organized and condensed.

**Comment by mhevery** [comment]
So we considered that when designing the routes. The solution was to put "private" things in non `index.tsx` files. So if a directory does not have `index.tsx` then it is private. 

Alternatively, you can put things outside of `src/routes` folder such as `src/component`

Even if you create `index.ts` by accident, it would not expose any of the code in that route. Can you explain a scenario where  you could see accidentally exposing code you did not intend?

**Comment by jessezhang91** [comment]
Yeah, putting non-index files is the approach we're taking right now but this request was more out of caution. Realistically, there shouldn't be any security implications from accidental exposure since we intend to put the components on the page anyway. I think it's more of "that's weird" from a router perspective.

With that said, @christinatka and I are happy to put a PR together. We explored the qwik codebase a little bit and identified what needs to change to support what is being recommended here if you guys think this is at least acceptable to explore.

---

For way more context than needed: this conversation stemmed from us reorganizing our codebase. We're attempting to merge together our home search codebase and our main website codebase. At the end of this, we're expecting over 150 Qwik components among many miscellaneous other ts files. Where we landed was a "feature module" folder structure alongside the routes folder. (It's what we're familiar with given our backgrounds in large Angular applications.)

However as @christinatka refactored in this direction, we noticed lots of one-off/unshared feature components that were route-specific. Rather than fully committing to the features folder structure, then, we decided to just leave these alongside the route they're specific to. So then, from a cleanliness "just-in-case" perspective, we thought it would be nice to have private folders (thus this ask).

**Comment by jessezhang91** [comment]
> Even if you create `index.ts` by accident, it would not expose any of the code in that route.

Just to clarify, when looking [here](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/utils/fs.ts#L148) I believe `index.ts` would match and be considered a route [here](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/routing/source-file.ts#L25-L26) (because of `isIndexModule` and `isModule`).

Our rationale for private directory is to just safeguard against this mistake but also acknowledge there isn't really a security implication here.

**Comment by jessezhang91** [comment]
Yeah, opting for simplicity here makes sense. We will probably still do the _private folder for our structure but noting no privacy/security concerns, we'll just add some custom eslint rules to prevent accidental index.tsx and whatnot.

Thanks for the feedback!
