### ISSUE TITLE
[🐞] Serializing a naked object, than wrapping it in store and serializing the store can confuse Qwik reactivity

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#5001]
### Which component is affected?

Qwik Runtime

### Describe the bug

If I have a deep reactive store value, and I `map` over an array a few level inside of it, I do not get updated values in my `.map()`. That seems to only happen if another prop is provided to a parent (`content` prop given to `EnableEditor`). 

### Reproduction

https://github.com/samijaber/reactivity-bug-repro/

### Steps to reproduce

- clone https://github.com/samijaber/reactivity-bug-repro/
- install
- run dev server
- click on `UPDATE TEXT` button

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 97.27 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.13.0/bin/yarn
    npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 116.1.57.47
    Chrome: 116.0.5845.96
    Firefox: 109.0.1
    Safari: 15.2
  npmPackages:
    @builder.io/qwik: ^1.2.8 => 1.2.8
    @builder.io/qwik-city: ^1.2.8 => 1.2.8
    undici: 5.22.1 => 5.22.1
    vite: 4.4.7 => 4.4.7
```

### Additional Information

If I remove the `content` prop from `EnableEditor`, everything works somehow: https://github.com/samijaber/reactivity-bug-repro/blob/5a2a498421e7dea36831973d80d5bc9a1b453e0e/src/sdk-src/content.tsx#L19-L21

**Comment by mhevery** [comment]
Understanding what is going on:

https://github.com/samijaber/reactivity-bug-repro/blob/simple-repro/src/routes/index.tsx#L4-L15
```typescript
export default component$(() => {
  const CONTENT = [
    {
      testName: "ORIGINAL",
    },
  ];
  return (
    <div>
      <ContentComponent blocks={CONTENT} />
    </div>
  );
});
```

First we declare `CONTENT` which is a naked object and we pass it to `<ContentComponent>` which forces the object to be serialized because it is part of the component props. The serialization process adds the object to the serialization map, effectively given the object an ID.

https://github.com/samijaber/reactivity-bug-repro/blob/simple-repro/src/sdk-src/content.tsx#L4-L34
```typescript
export const ContentComponent = component$<{
  blocks: { testName: string }[];
}>((props) => {
  const state = useStore(props.blocks); // BROKEN
  // const state = useStore(clone(props.blocks)); // WORKS

  return (
    <EnableEditor
      // LOOK HERE!!!
      // COMMENT THIS `unused` PROP OUT TO SEE THE CODE WORK.
      // unused={'anything'} // WORKS
      // unused={props.blocks} // BROKEN
      // unused={props.blocks[0]} // BROKEN
      // unused={props.blocks[0].testName} // BROKEN
      contentState={state[0]} 
    >
      <div>BLOCKS (outside loop): {state[0]?.testName}</div>
      {state.map((block, idx) => (
        <div key={idx}>
          BLOCKS (inside loop): <span>{block.testName}</span>
        </div>
      ))}
    </EnableEditor>
  );
});
```

Inside the `<ContentComponent>`, the `CONTENT` is now wrapped into a Store, which wraps the naked object in a proxy to add reactivity. The reactive version is used to read `testName` property, which we expect to be reactive. 

Everything above works as expected. Now for the issue:

Let's uncomment  the `unused` property binding on `<EnableEditor/>`
```jsx
<EnableEditor
      unused={props.blocks[0].testName} // BROKEN
      contentState={state[0]}
    >
```

By referring to the naked object, we have now confused Qwik which now thinks that all references are now naked and it fails to set up reactivity for the JSX. When looking into the `qwik/json` you can see that reactivity did not get set up.

**Comment by mhevery** [comment]
Even Simpler example:
```typescript
import { component$, useStore } from "@builder.io/qwik";

export default component$(() => {
  return <Parent nakedState={[0]} />;
});

export const Parent = component$<{ nakedState: [number] }>(({ nakedState }) => {
  const state = useStore(nakedState);
  return (
    <>
      <Button
        // Uncommenting the next line breaks the code. (UI no longer updates)
        // unusedValue={nakedState}
        state={state}
      />
      <ul>
        {state.map((v, idx) => (
          <li key={idx}>{v}</li>
        ))}
      </ul>
    </>
  );
});

export const Button = component$<{ unusedValue?: [number]; state: [number] }>(
  ({ state }) => {
    return <button onClick$={() => state[0]++}>+1</button>;
  }
);
```
