### ISSUE TITLE
[🐞] Incorrect svg/path size

### ISSUE THREAD

**Issue by Kasheftin** [BuilderIO/qwik#5006]
### Which component is affected?

Qwik Runtime

### Describe the bug

##Source Code##
https://github.com/Kasheftin/qwik-svg-bug

##Repro##
![Peek 2023-08-24 20-21](https://github.com/BuilderIO/qwik/assets/379267/1922d81d-4fdb-4c16-9c19-23994731a1e2)

### Reproduction

https://github.com/Kasheftin/qwik-svg-bug

### Steps to reproduce

1. Load the page
2. Svg icon is shown correctly (200x200px)
3. Click on the button to change the icon, then click again to change it back
4. Svg icon size is not respected anymore, now it's 24x24px. More precisely, SVG element has the same size, it's correct. But the path inside is not scaled up. However path element is exactly the same as it was before.

### System Info

```shell
"@builder.io/qwik": "^1.2.8",
"@builder.io/qwik-city": "^1.2.8",
```

**Comment by mhevery** [comment]
HTML attribute names are case-insensitive.
BUT SVG attributes are case-sensitive. 🤯  (I know)
Turns out that parsing HTML the HTML parser fixes the `viewbox` to `viewbox`, but when you render on the client, than `setAttribute` honors the lower case `viewbox`

So in your example switch `viewbox` to  `viewBox`  and all is good .

```typescript
export default component$((props: Props) => {
  const size = props.size || 16;
  if (icons[props.name]) {
    return (
      <svg
        viewBox="0 0 24 24"  // <====== HERE
        width={size}
        height={size}
        data-icon={props.name}
        class={props.class}
      >
        <path d={icons[props.name]} />
      </svg>
    );
  } else {
    return <div data-icon-not-found={props.name} />;
  }
});
```

It is moments like these when you want to scream into void!
