### ISSUE TITLE
Typed Slots [✨]

### ISSUE THREAD

**Issue by Grawl** [BuilderIO/qwik#5114]
### Is your feature request related to a problem?

I cannot find any information about how to type slots.

### Describe the solution you'd like

Currently, type of `q:slot` property is just a `string`.

The type definition of `component$` is following:

```ts
export declare const component$: <
    PROPS = unknown, 
    ARG extends {} = PROPS extends {} ? PropFunctionProps<PROPS> : {}
>(
    onMount: OnRenderFn<ARG>
) => Component<PROPS extends {} ? PROPS : ARG>;
```

I suggest to add a union generic parameter to `component$` to type slots:

```ts
export declare const component$: <
    PROPS = unknown, 
    ARG extends {} = PROPS extends {} ? PropFunctionProps<PROPS> : {},
    SLOTS extends string // <- I suggest to add something like this
>(
    onMount: OnRenderFn<ARG>
) => Component<PROPS extends {} ? PROPS : ARG>;
```

So, the declaration of component will be like this:

```tsx
type MyComponentProps = {
    count: number
}

type MyComponentSlots = 'foo' | 'bar'

export const MyComponent = component$<MyComponentProps, {}, MyComponentSlots>((props, slots) => {
    return (
        <div>
            <span>{props.count}</span>
            <Slot name={slots.foo}/>
            <Slot name={slots.bar}/>
        </div>
    );
})
```

And we can use it in other components like this:

```tsx
export const OtherComponent = component$(() => {
    return (
        <div>
            <MyComponent count={1}>
                <Slot name='foo' />
                {/* Here    ^   will be autocomplete */}
                <Slot name='bar' />
                <Slot name='qux' />
                {/* Here    ^   will be type error because there is no slot named 'qux' */}
            </MyComponent>
        </div>
    )
})
```

### Describe alternatives you've considered

In plain React, I will solve this problem with regular prop, like this:

```tsx
type ComponentProps = {
  count: number
  slots: {
    foo: ReactNode
    bar: ReactNode
  }
}
export const ComponentWithSlots: FC<ComponentProps> = (props) => {
  const { count, slots } = props
  return (
    <div>
      {slots.foo}
      <span>{count}</span>
      {slots.bar}
    </div>
  )
}
```

So I will have typescript support over slots:

```tsx
<ComponentWithSlots
  slots={{
    foo: <span>Foo</span>,
    bar: <span>Bar</span>,
  }}
  count={2}
/>
```

### Additional context

I am a novice with Qwik and I like how it goes so far, but lack of TypeScript support seems like a blocker for me and my team.

**Comment by mhevery** [comment]
I like your suggestion; unfortunately, TypeScript does not have sufficient type expressiveness to describe what you are looking for.

In the case of React, you are passing the slots as a prop, which is different than restricting the child `<Slot>` component.

So while we would like something like this, as of right now TS is the blocker.



> I am a novice with Qwik and I like how it goes so far, but lack of TypeScript support seems like a blocker for me and my team.

Qwik leans heavily on TS and we have very good TS support in most cases. It is just this case is a limitation of TS and how Qwik uses Slots. See https://qwik.builder.io/docs/components/slots/#projection-vs-children for a discussion why Qwik does things differently.

If it is OK with you I will close this issue since it will be "won't fix" because it is a limitation of TS.
