### ISSUE TITLE
[🐞] Props spreading 

### ISSUE THREAD

**Issue by motss** [BuilderIO/qwik#5292]
### Which component is affected?

Qwik Runtime

### Describe the bug

When spreading props in a component, any prop that comes after the spreading does not override the prop values as expected, e.g. `{...props} class={['button', props.class]}` and `button` will be overridden by props.class.

## Expected behavior

```ts
<button {...props} class={['button', props.class]}>...</button>
// Assume props.class contains `a b`
// The final value of class should be `button a b`
```

## Actual behavior

```ts
<button {...props} class={['button', props.class]}>...</button>
// Assume props.class contains `a b`
// The final value of class will be `a b`
```

### Reproduction

https://qwik.builder.io/playground/#v=1.2.13&f=7VdNT8JAEP0ra0woh7JWo4mWDxMSbxqN0RMhobRFiKRtAAOG9L%2F7Zmb7DcSriRwoOzudnZl9M%2FOogObOyeLhe9mj92G2U8M8hZwDQLMVYd8uTbnSbzPlToJRskYhD5ltIHeF9R6OIsfu3cLBrkoH7TZTkjzHjbk64fC1EBhWoQ%2FiR6vyMHBclHAUdo0cvQReVWUzlJuLljlHoW8yoR8vY%2BjVpMVQ6hxRMPYvk51Ci18E6txxnOpuZ%2BUFiy%2BA9jrZZTuJFwSAp6tuC5k5YRUGIknxPcEN44Fx%2Bx6ZgclzfYbeGG%2BJjBkp%2BADYCjrthshFCHLE%2BaG%2BYkoCGmj69OCDtJiVSzKXQURwbSutdYKb7Qs7JGegWAI7VoRUPiFbKrWn18hns2aL%2Ff3IEkXLJuPjXIHgazR7BDSBuZjO6KkI8hS8vD4PHx%2BeXJk1QYxoI7y4jVefZ41yzN3LfaNg6PjDzvG2Zjk7KR7W3Kv6RtVHzv2m65a4IiFYewa6BMbOGtPGVVeOYCGlcPW0rLANFx9zgPZGsCUavtFogtT%2F9iLRIwSR8pFWVZ8BmbxUtHmmPCRpNPOW4CmtlrKmWDIvooVvjcfp4A3szPyVIMLYuyjM1JvW%2F6T5k5PmBw

### Steps to reproduce

1. Go to the reproduction URL.
2. You will see a rendered page with a button
3. Comment/ uncomment the code to see the result
4. Expected behavior is that `.button` should be applied but it is not due to missing `button` after props spreading.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.84 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/Library/Caches/fnm_multishells/15262_1696916828039/bin/node
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/15262_1696916828039/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0
    Safari Technology Preview: 17.4
  npmPackages:
    @builder.io/qwik: ^1.2.13 => 1.2.13 
    @builder.io/qwik-city: ^1.2.13 => 1.2.13 
    undici: 5.25.4 => 5.25.4 
    vite: 4.4.11 => 4.4.11
```

**Comment by gioboa** [comment]
I will look at it

**Comment by wmertens** [comment]
I think this is an optimizer bug. In the posted playground, go to the SSR Module tab, and you'll find the button code at the top.

Now move the {...props} to after the class and observe nothing changed in the `_jsxS()` call. (you need to switch tabs for it to update the code!).

So by splitting into mutable and immutable props, the optimizer can't handle ...props properly. I think it needs to mirror the class prop in the mutableprops at the correct location, and the renderNode function needs to be careful about mutable props overwriting immutable props.

**Comment by wmertens** [comment]
The problem is in the Rust function [`internal_handle_jsx_props_obj`](https://github.com/BuilderIO/qwik/blob/dec9d5685f2db6c7134a1126424083f64fb6d90a/packages/qwik/src/optimizer/core/src/transform.rs#L1164) which is indirectly called by
 [`handle_jsx`](https://github.com/BuilderIO/qwik/blob/dec9d5685f2db6c7134a1126424083f64fb6d90a/packages/qwik/src/optimizer/core/src/transform.rs#L753). It sees that there's a ...prop and sets `dynamic_props` and then [when `is_fn || dynamic_props` it copies the correct structure](https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/optimizer/core/src/transform.rs#L1236) into `mutable_props`, but then later it does some things only when `is_fn`.

This eventually results in the `handle_jsx` picking _jsxS instead of _jsxC, with the wrong mutable props structure.

Note: if you do the spread on a component$ it works correctly, you can inspect the SSR module to see the difference in code:

https://qwik.builder.io/playground/#v=1.2.13&f=7VddSwJREP0rtwI10FW3pFg%2FgoXeiiLqSQRXV3NJdhc1NGT%2Fe2dm7n76QUQ9BO2Dy52dnZ0798ycYxY0rYureD98LlvMPnA7DcxjyNkDtKoi7FczLHcUelIj2qDN2gKVSmN1EJjSuLHSdNoq6lUqLECSimYYdcjbNESo8EO6sE%2BMJAfEYqFV%2FUlb2zEzkE%2FeNkVbWRiNMzT0KjaOg3kAv4I1JZ%2FaAQcdvxluFEa556qzRqORf1pbOK73DnBehpv4Sei4LmBoqevUpr%2BwmLhiifA7xEniBlp98TUxMn9PMQODNYkubQXvQ5Vgoq5IREwggrg%2BND809OGB4U43%2FpAhYeV49DGQ4FtWlWEYIc60KyqQkoFjBtRYESL5C%2FFSqS29RjnrNUfsbvtlcSxXKfggcSCYas8OAUrgLKFjGSqGpASPTw%2F23e29JZziBtitjxfXweLtZKftkvTo8tzu6TQImqd6zbnS5iid%2FcnyY4PtnLRkXEg3nyt1HSUrNbXzSIcgI1gzpHVyumQ9DljvJaHOd5rG%2FFbX5Ati52th%2FkYt7GwZvkI6hcY2HN3R1KO1JcjWUmZDWiQiFBijrMN64r3O0MstaTnxGGuP3d4dfzi%2B%2BFFjkfOBSV2kwNiemWJJkRzUpz915pBppZIqj7BkWUiLcXkwiHrPEKf6nxTp5U49DbMnsvlDoc0iH%2FyT%2BJ8k8U8

**Comment by wmertens** [comment]
As a workaround, you can do `const Button = 'button'; <Button ...`, which will trick the optimizer into doing the right thing
