### ISSUE TITLE
[🐞] Playground is broken in 1.2.15

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#5371]
### Which component is affected?

Qwik Playground

### Describe the bug

Error is

```
ReferenceError: require is not defined at globalThis.qwikOptimizer.module.exports.exports (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:2434:25) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:3561:2) at g (https://qwik.builder.io/repl/repl-sw.js:1:377) at async N (https://qwik.builder.io/repl/repl-sw.js:1:1086) at async K (https://qwik.builder.io/repl/repl-sw.js:12:5471)
```

which might mean a bundling issue.

The commits involved are https://github.com/BuilderIO/qwik/compare/v1.2.14...v1.2.15 which don't immediately have anything suspect.

### Reproduction

https://qwik.builder.io/playground/#v=1.2.15&f=G000o4mG5EQDAA

### System Info

```shell
website
```

**Comment by wmertens** [comment]
paging @bluwy, your commit https://github.com/BuilderIO/qwik/commit/ec53ef7834dd76af0fca1f90c903d93f6cb802f6 is the only one that touched the optimizer, I'm assuming the build pulls in the new vitefu package that somehow uses require

**Comment by bluwy** [comment]
Hmm seems like it. `packages/qwik/dist/optimizer.cjs` `require`s some modules now because I thought it's safe to run in node. The esbuild script also bundles for `platform: 'node'`. 

I suppose the fix is to import it [here](https://github.com/BuilderIO/qwik/blob/ab67f91f707ad3baa6e15499d11753e84f7b9a9b/packages/qwik/src/optimizer/src/plugins/vite.ts#L689) but I'm not really sure how that can be done with dependencies bundled, or maybe `vitefu` cannot be bundled. Not familiar with how the project is bundled 😅 

At the meantime, I don't mind if we revert that PR, and then figure it out the fix for Vite 5 later.

**Comment by mhevery** [comment]
Reverting: https://github.com/BuilderIO/qwik/pull/5379
