### ISSUE TITLE
[DISCUSSION] Exploring component-based routing

### ISSUE THREAD

**Issue by mahmoudajawad** [BuilderIO/qwik#543]
### Is your feature request related to a problem?

Modern frameworks tend to provide, built-in or on-side, routing solution. Qwik doesn't.

### Describe the solution you'd like

Implement a solution to allow using different components as views to replicate SPA routing behaviour.

### Describe alternatives you've considered

HTML routing. However, for modern applications this is considered not-so-welcome experience.

### Additional context

I've run my attempt at creating a routable app. And, this is what I got to:
```tsx
import { useStore, component$, Host, Component } from "@builder.io/qwik";
import { Logo } from "../logo/logo";

import "./global.css";

export const HomePage = component$(({ greeting }: { greeting: string }) => {
  return <h1>Home Page {greeting}</h1>;
});
export const AboutPage = component$(({ greeting }: { greeting: string }) => {
  return <h1>About Page {greeting}</h1>;
});

export const ROUTES: Record<string, Component<any>> = {
  "/": HomePage,
  "/about": AboutPage,
};

export const App = component$(() => {
  const state = useStore({
    greeting: "world!",
    route: "/",
  });
  return (
    <Host class="my-app p-20">
      <Logo class="mb-10" />

      <h1 class="text-3xl mb-2">Congratulations Qwik is working!</h1>

      <a
        href="/#/about"
        onClick$={() => {
          state.route = "/about";
        }}
      >
        About
      </a>

      <li>
        Try interacting with this component by changing{" "}
        <input
          value={state.greeting}
          class="border-2 border-solid border-blue-500"
          placeholder="Write some text"
          onInput$={(event) => {
            const input = event.target as HTMLInputElement;
            state.greeting = input.value;
          }}
        ></input>
        .
      </li>
      <li>
      <li>
        Observe that the binding changes: <code>Hello {state.greeting}!</code>
      </li>

      {ROUTES[state.route]({
        greeting: state.greeting,
      })}
    </Host>
  );
});
```

The above example, brings routing which replicates something like Angular, where we define a map of routes, which Angular uses to replace a `router-outlet` with the appropriate component matching the route. Now, only if I figured my way through the following attempt:
```tsx
  const state = useStore(() => {
    const route = global.window.location.hash.replace("#", "");
    return {
      greeting: "world!",
      route,
    };
  });

```
I would also be able to get the route from current document location.

Overall, does this get inline with how Qwik team is looking at routing? Does the team already have some other approach that can be shared with the community so might we collectively can shape it?

**Comment by isaac-mcfadyen** [comment]
Looks like Qwik City is going to be how they're approaching routing. Starter for a Qwik City app just got merged alongside 0.0.21 if you want to test it out! 🙂

**Comment by mahmoudajawad** [comment]
Right. I'm checking that now. I still want to look into something that is component-based and not file-based.
I'll try to look under the hood to see how qwik-city picks the path and implement it further to see whether I can do something that is interactive and doesn't break qwik core functionality.

**Comment by manucorporat** [comment]
@mahmoudajawad component based should be easy to implement, to be honest, we are still experimenting with different ideas:

For example for our internal testing, we have a super simpler router: https://github.com/BuilderIO/qwik/blob/e5967d8803e6c6df67f87456220caca0c799c9f1/starters/apps/e2e/src/entry.ssr.tsx#L24-L38

**Comment by manucorporat** [comment]
So far, we want to have qwik-city to be the starter that provides some file based routing, but you will be able be able to inject a router at the root, and skip the whole qwik-city router

**Comment by mahmoudajawad** [comment]
Wow! I'm amazed with how things can get very simple in Qwik-land. I've refactored my sample routing around this now:
```tsx
import { FunctionComponent, useStore } from "@builder.io/qwik";
import { renderToString, RenderToStringOptions } from "@builder.io/qwik/server";
import { manifest } from "@qwik-client-manifest";
import { AboutPage, HomePage } from "./components/app/app";
import { Root } from "./root";

export function render(opts: RenderToStringOptions) {
  let url = typeof opts.url === "string" ? new URL(opts.url) : opts.url!;

  const tests: Record<string, FunctionComponent> = {
    "/": () => <HomePage greeting="Home!" />,
    "/about": () => <AboutPage greeting="About!" />,
  };
  const Test = tests[url.pathname];

  return renderToString(
    <html>
      <head>
        <meta charSet="utf-8" />
        <title>Qwik Blank App</title>
      </head>
      <body>
        <a
          href="#"
          onClick$={() => {
            url = new URL("http://localhost:3000/about");
          }}
        >
          About
        </a>
        <Test />
      </body>
    </html>,
    { debug: true, qwikLoader: { include: true, events: ["click"] }, ...opts }
  );
}
```

which is now rendering per route, correctly, however, I failed to find a method to dynamically change the route, as setting value to `url` wouldn't trigger a state-change, nor using `useState` is allowed here. Any suggestions on how to implement this final bit?

**Comment by mahmoudajawad** [comment]
I think I'm making progress. With following code I'm getting the routing behaviour but while managing the routing on component level, rather than on renderer level, which seems like implying a lot of restrictions. Now, everything would be perfect if Qwik understand that I used `e.preventDefault` in the callable for `onClick` event, and getting the same to be applied to the anonymous callable it creates dynamically. Is there a method to apply that?

Also, How can I tell whether passing `url` down to `App` component is not a bad idea, or doesn't break Qwik behaviour? IOW, how can I make sure that what I'm trying to achieve wouldn't results in working app, but breaks the core concepts of Qwik?

`entry.ssr.tsx`
```tsx
import { renderToString, RenderToStringOptions } from "@builder.io/qwik/server";
import { manifest } from "@qwik-client-manifest";
import { Root } from "./root";

/**
 * Entry point for server-side pre-rendering.
 *
 * @returns a promise when all of the rendering is completed.
 */
export function render(opts: RenderToStringOptions) {
  return renderToString(<Root opts={opts} />, { ...opts, manifest });
}
```

`root.tsx`
```tsx
import { RenderToStringOptions } from "@builder.io/qwik/server";
import { App } from "./components/app/app";

export const Root = ({ opts }: { opts: RenderToStringOptions }) => {
  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <title>Qwik Blank App</title>
      </head>
      <body>
        <App opts={opts} />
      </body>
    </html>
  );
};
```

`app.tsx`
```tsx
import {
  useStore,
  component$,
  Host,
  FunctionComponent,
} from "@builder.io/qwik";
import { RenderToStringOptions } from "@builder.io/qwik/server";
import { Logo } from "../logo/logo";

import "./global.css";

export const HomePage = component$(({ greeting }: { greeting: string }) => {
  return <h1>Home Page {greeting}</h1>;
});
export const AboutPage = component$(({ greeting }: { greeting: string }) => {
  return <h1>About Page {greeting}</h1>;
});

export const ROUTES: Record<string, FunctionComponent> = {
  "/": () => <HomePage greeting="Home!" />,
  "/about": () => <AboutPage greeting="About!" />,
};

export const App = component$(({ opts }: { opts: RenderToStringOptions }) => {
  const route =
    typeof opts.url === "string" ? new URL(opts.url).pathname : "/#/";
  const state = useStore({
    greeting: "world!",
    route,
    router: ROUTES[route] || ROUTES["/"],
  });

  return (
    <Host class="my-app p-20">
      <Logo class="mb-10" />
      <h1 class="text-3xl mb-2">Congratulations Qwik is working!</h1>
      <a
        href="/"
        onClick$={() => {
          state.route = "/";
        }}
      >
        Home
      </a>{" "}
      <a
        href="/about"
        onClick$={(e) => {
          e.preventDefault();
          state.route = "/about";
        }}
      >
        About
      </a>
      <li>
        Try interacting with this component by changing{" "}
        <input
          value={state.greeting}
          class="border-2 border-solid border-blue-500"
          placeholder="Write some text"
          onInput$={(event) => {
            const input = event.target as HTMLInputElement;
            state.greeting = input.value;
          }}
        ></input>
        .
      </li>
      <li>
        Observe that the binding changes: <code>Hello {state.greeting}!</code>
      </li>
      <state.router />
    </Host>
  );
});
```

**Comment by mahmoudajawad** [comment]
@manucorporat, I think you can convert this issue into a discussion thread which seems more appropriate for it now.

**Comment by nnelgxorz** [comment]
I think the reason preventDefault isn't working is because the onClick$ is essentially async, so there's no guarantee it's parsed and executing at the time of the first click.

Maybe adding a useClientEffect$ on the document body to catch click events and prevent default if the event targets are a tags and the hrefs not to external pages?

`
useClientEffect$(() => {
    document.addEventListener('click', (e) => {
      let target = e.target as HTMLElement;
      let href = target.getAttribute('href');
      if (target.tagName === 'a' && href && href.startsWith('/')) {
        e.preventDefault();
      }
    })
  });
`

**Comment by nnelgxorz** [comment]
@mahmoudajawad Looks like this is a little more involved than I thought. Forgive my ignorance, but I've never done client side routing from scratch before. I guess browsers don't like you messing with navigation events (for good reason). In this case, it's probably best to not use anchor tags for your client navigation.

Something like [this works better.](https://qwik.builder.io/playground#version=0.0.24&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwaW1tdXRhYmxlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwTElOS1MlMjAlM0QlMjBpbW11dGFibGUoJTdCJTVDbiUyMCUyMCUyMCUyMCU1QyUyMkhvbWUlNUMlMjIlM0ElMjAlNUMlMjIlMkYlNUMlMjIlMkMlNUNuJTIwJTIwJTIwJTIwJTVDJTIyQWJvdXQlNUMlMjIlM0ElMjAlNUMlMjIlMkZhYm91dCU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJDb250YWN0JTVDJTIyJTNBJTIwJTVDJTIyJTJGY29udGFjdCU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJHaXRodWIlNUMlMjIlM0ElMjAlNUMlMjJodHRwcyUzQSUyRiUyRmdpdGh1Yi5jb20lMkZCdWlsZGVySU8lMkZxd2lrJTJGJTVDJTIyJTVDbiU3RCklNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMFN0YXRlJTIwJTdCJTVDbiUyMCUyMHBhZ2UlM0ElMjBzdHJpbmclNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyME5vdExpbmslMjAlM0QlMjBjb21wb25lbnQlMjQoKHByb3BzJTNBJTIwJTdCbGFiZWwlM0ElMjBzdHJpbmclMkMlMjBocmVmJTNBJTIwc3RyaW5nJTJDJTIwc3RhdGUlM0ElMjBTdGF0ZSU3RCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHdpbmRvdy5oaXN0b3J5LnB1c2hTdGF0ZSglN0IlN0QlMkMlMjAnJyUyQyUyMHByb3BzLmhyZWYpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHByb3BzLnN0YXRlLnBhZ2UlM0Rwcm9wcy5sYWJlbCUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTNFJTdCcHJvcHMubGFiZWwlN0QlM0MlMkZidXR0b24lM0UlNUNuJTdEKSU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUzQSUyMFN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCcGFnZSUzQSUyMCU1QyUyMkhvbWUlNUMlMjIlN0QpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDaGVhZGVyJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2gxJTNFJTdCc3RhdGUucGFnZSU3RCUzQyUyRmgxJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmhlYWRlciUzRSU1Q24lMjAlMjAlMjAlMjAlM0NuYXYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDdWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdCT2JqZWN0LmVudHJpZXMoTElOS1MpLm1hcCgoJTVCbGFiZWwlMkNocmVmJTVEKSUyMCUzRCUzRSUyMCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NsaSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0JocmVmLnN0YXJ0c1dpdGgoJTVDJTIyJTJGJTVDJTIyKSUyMCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0YlMjAlM0NOb3RMaW5rJTIwbGFiZWwlM0QlN0JsYWJlbCU3RCUyMGhyZWYlM0QlN0JocmVmJTdEJTIwc3RhdGUlM0QlN0JzdGF0ZSU3RCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0ElMjAlM0NhJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwc3RhdGUucGFnZSUyMCUzRCUyMGxhYmVsJTdEJTIwaHJlZiUzRCU3QmhyZWYlN0QlM0UlN0JsYWJlbCU3RCUzQyUyRmElM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmxpJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCklN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGdWwlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGbmF2JTNFJTVDbiUyMCUyMCUzQyUyRmJvZHklM0UlM0IlNUNuJTdEKSUzQiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZwbGF5Z3JvdW5kJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlclRvU3RyaW5nT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjByZW5kZXIob3B0cyUzQSUyMFJlbmRlclRvU3RyaW5nT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcGxheWdyb3VuZCUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)

[This article](https://www.willtaylor.blog/client-side-routing-in-vanilla-js/) covers the implementation in a basic way.
[This article](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role) goes over some of the accessibility issues when using fake links instead of real anchor tags.

Hope that's helpful!

**Comment by mahmoudajawad** [comment]
Thanks for the links, @nnelgxorz, and thanks for your attempt to work with me on this. I really appreciate it.

I'm sure I need to dig more into this. I'm considering manipulating internals of Qwik to see whether adding `preventDefault` to the callable created by Qwik would make a difference. This IMO is better approach that using proxy elements acting as links because this anti-semantic approach definitely is going to break in some way, and I'm hoping to reach a point where I can have client-side routing, that is in consistent with regular routing.

**Comment by mahmoudajawad** [comment]
Thanks a lot, @IgnusG, I think your work will eventually take me to the state I'm looking for.

For instance, looking at first snippet, on which version of Qwik did that work for you? That snippet never worked for me, but I was able to tinker with a version that mixes between your approach and what @nnelgxorz had suggested earlier and it seems to do the trick, but comes in a very fine spaghetti dish.

I'll try to clean that up more.

**Comment by mahmoudajawad** [comment]
@manucorporat, does #627 touch in anyway on this? I 2as looking at the changes it introduces and it seems to build on SPA-like behaviour. If this is correct does it mean all I need now to get SPA behaviour with Qwik is using Link rather than anchor?

**Comment by nnelgxorz** [comment]
@mahmoudajawad this got snuck in a little under the radar, but Qwik City has SPA routing now.

packages/qwik-city/runtime/src/library/link.tsx

**Comment by mahmoudajawad** [comment]
@nnelgxorz, you guys rock! Thanks for your work. Judging by the version, this isn't release yet, right?

**Comment by nnelgxorz** [comment]
100% percent credit goes to @manucorporat. I just remembered to remind you.

The SPA Link component is in the current release of Qwik City if you want to take it for a spin. :+1:

**Comment by nnelgxorz** [comment]
Oh, the really crazy part is you only get SPA behavior when you use a Link component. All your regular links are still MPA. You have both routing options available at the same time and can choose which one is best whenever you want. 👀

**Comment by dannyfranca** [comment]
I recently needed to create a Component Router for a micro-frontend with Cloudflare Workers/Qwik project.

I created a router similar to react-router and vue-router and have successfully used it in production.

I created a public package to share that work at [https://github.com/dannyfranca/qwik-router](https://github.com/dannyfranca/qwik-router).

I'll keep working on that project during the following weeks if more people are interested in it.

**Comment by md-owes** [comment]
> I recently needed to create a Component Router for a micro-frontend with Cloudflare Workers/Qwik project.
> 
> I created a router similar to react-router and vue-router and have successfully used it in production.
> 
> I created a public package to share that work at https://github.com/dannyfranca/qwik-router.
> 
> I'll keep working on that project during the following weeks if more people are interested in it.

@dannyfranca, this is a much-needed dependency for my new project. Let me know if i can contribute.

**Comment by dannyfranca** [comment]
> > I recently needed to create a Component Router for a micro-frontend with Cloudflare Workers/Qwik project.
> > I created a router similar to react-router and vue-router and have successfully used it in production.
> > I created a public package to share that work at https://github.com/dannyfranca/qwik-router.
> > I'll keep working on that project during the following weeks if more people are interested in it.
> 
> @dannyfranca, this is a much-needed dependency for my new project. Let me know if i can contribute.

@md-owes It is V1 already. Anyone can contribute. just check the [CONTRIBUTING](https://github.com/dannyfranca/qwik-router/blob/main/CONTRIBUTING.md) guidelines
