### ISSUE TITLE
[🐞] Slot projected content not updating DOM

### ISSUE THREAD

**Issue by intellix** [BuilderIO/qwik#5506]
### Which component is affected?

Qwik Runtime

### Describe the bug

I've got a toggle component inside another component with Slot projection (like an accordion). When you click the toggle it updates a Signal and is supposed to change state. In 1.2.13 it appears to work fine, but then in 1.2.14 it stopped and the view/DOM never changes, despite everything logging. 

I would love to send a PR but I have honestly no idea how the change stuff works or where to begin looking. I've tried to narrow down the reproduction to be as simple as possible. 

### Reproduction

https://stackblitz.com/edit/qwik-starter-yajeyx

### Steps to reproduce

npm install && npm run dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.14 => 1.2.14 
    @builder.io/qwik-city: ^1.2.14 => 1.2.14 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

I feel like it works if the initial content isn't delivered by SSR, so it could be related to that.

**Comment by wmertens** [comment]
Here's the same thing in a playground (minus the CSS), easier to switch versions: https://qwik.builder.io/playground/#v=1.2.19&f=7VhNb9pAEP0rK1QJDrYTIJdamLRBQT00t0g9VJWCYWNQqI34SGgt%2FnvfzK7XYwMpjVRVlUBCsmd3Z2Z33sy%2BsQBNtysihQnvPAECz128niJce5gALC6G9nDpnTwcTEdpom%2BfsaYQDYH2VUVyl0GZlZwASQbJfZYkc00mVzhI8q%2B4d6%2FDiie9libNYc1S79P93WfmBbdzTcnX51g8Z7MJ4Ku4XoaWpdD7eKpRWSZQHmcgEaOUhFnKGo6aNHtSuBvJQqjqNqsmsQE%2BrT11HCUDDaXEbsTh7m%2BHDpfnHzPO4%2BzBJn0CX0ghsH7czDfLI14I82UgD1g%2FYdPGHkBXzQ0TWQS1RFtPRLvfauUu1p4KgoCJp9q5XJI8r2mX9gsyYuMYNj1DWAMrAPzt0jXYIDHaARFZ3DeReiD055Xp6lo148RPllqn%2FtXlZVOFLFjqCb%2FusORBqERJn%2BHayJa%2F1cqka45S7m%2F9K1YrJfuaQU3pat9BI%2BuiCB6pJmDshp5Hje%2Bx326I4hD3B9YFZj4h6gMO0xa%2B6kGRA6ZsUAdQvMwowk5fXoSlmKzUbBLl5Gkpsa68%2BJdqin%2B2GI1n6x94GsWIHxHXuX5c%2B1%2F99%2FxbbL813FqqAVGDXYqzbSEvy5shmOCu1qg1lldCuyu5el487cShcCdiF9YDuOuvDU7bvQuaVxZWNl2vrASvAyjvvAbzRQXRFOlDsKe4n0H%2FF0B%2FBvxhwHfeBviP43G2nBDvkpA%2FQCaJTmBjVodja%2BNMgwjfmMu3Bba9cfdzhbTxiIqiiDC00U3Ai3uuUD2O5itNrO0kbms%2FRvDHisixHdw91rTVTk4Wk90FjgVSVTGONtT0x5HRGxzwtcle2hSAiLTXstuZoXwWijxngH1SVSNukMb4aOsp4yIkc0egYyHyqCvyiDPpZpOY%2FPlC%2FeyaOzjGyxK9IlrsFTfFaBV5qAQDk0dqgoU6CzTzbQibQJlbYfUYyxMV6%2FUL6g8H9YIPKyhdRO9xqr9ol57YYyFPF%2FhEourU80M76ATtqz25T9lrB9%2FiwnC2%2FRMHuq850D3igImBsGCLWpRX80lAxdU7%2BjmsccEwj3Kcak3UMAH7WVYrV5ecC51%2F54Oo272LCshtoTo3qv9fo%2FoL

Notice that in Toggle2 I moved the props out to a separate line, and if I did it to Toggle by itself it made Toggle work, but with Toggle2 in the file it makes the original Toggle work.

Very odd, seems like the optimizer is involved somehow, but that didn't change in 1.2.13.

**Comment by wmertens** [comment]
FYI still working on this. The minimal repro is this, the problem is that the SSR doesn't register the listeners when the child is in a slot.

https://qwik.builder.io/playground/#v=1.2.19&f=7ZdLS8NAEID%2FyiDFJDQNgngJ3RQED95EvInQNF3T0NiIUVCW%2Fe%2FOzD7jC6%2BCt3Qf8%2Fx2ZhpDc3oWMjXLIwLy0IBzIKpztuYSU90dxq656CWXY9zkQ7%2FAjBN%2FM7RtLxHpxxGD86XI26SjXp7cwTEourQqIWl2stlvhtckp9qJK1bth6Ab8Sg5eLKMVFZpqnzzzqEoCp5oQPskxQNEYq9WrsuxEXJbohF8r7ALedSQMcbfpprGqeWmMo2HfN5iw%2BMu480tMWtoicVxoiXTsABlljAG2oxnTja32wgFjiEo56Lm8IsjF8cj54wIEgusby9SY4B4mJoJ5UKF1ZxGBx3gAng2oX6QHrfIBMcbcJWY5ohouqoxpPQ8PtWcJW2jHrrmn3EzSKyQ5wNmpj6kbGZpx8vJa%2BYdEEJAQk0Y4QuA%2FFjl7FjatWiSBz81QjK%2FbzGIj5yEXQzWrj60coYHYtluHycUMzoJUmSCHdkKK0ju637EL%2BTdmu9uOyTXXkkJMxXlbFHhb6dBr5lCiPV49bTDSQmYWkKZTwMndkumc8RklECKYtw4RzaFe%2FkmlAmMtWWC%2B4T1IM0enSJsH68Hc5p1fwvfgY8CI2o%2BNXkr2NSoBm6eom%2F%2BFxOGd5VmoopNn891dS1tlgm7vkMX%2Fd8fS3ZwnlaQ9Oy%2FFf7RVvgO
