### ISSUE TITLE
[✨] Improve Runtime performance and Memory Footprint

### ISSUE THREAD

**Issue by n4bb12** [BuilderIO/qwik#5944]
### Is your feature request related to a problem?

Qwik's strength lies in startup performance and delaying work as much as possible. Delaying, however, is not avoiding. Eventually, work needs to be done.

When it comes to performing work, especially, regarding list data: adding, removing, updating, and re-organizing DOM elements, Quick is only faster than React but slower than Angluar and Vue, and much slower than Svelte.

[js web frameworks benchmark](https://krausest.github.io/js-framework-benchmark/2023/table_chrome_120.0.6099.62.html#eyJmcmFtZXdvcmtzIjpbImtleWVkL2FuZ3VsYXItY2YiLCJrZXllZC9xd2lrIiwia2V5ZWQvcmVhY3QtaG9va3MiLCJrZXllZC9zdmVsdGUiLCJrZXllZC92YW5pbGxhanMiLCJrZXllZC92dWUiXSwiYmVuY2htYXJrcyI6WyIwMV9ydW4xayIsIjAyX3JlcGxhY2UxayIsIjAzX3VwZGF0ZTEwdGgxa194MTYiLCIwNF9zZWxlY3QxayIsIjA1X3N3YXAxayIsIjA2X3JlbW92ZS1vbmUtMWsiLCIwN19jcmVhdGUxMGsiLCIwOF9jcmVhdGUxay1hZnRlcjFrX3gyIiwiMDlfY2xlYXIxa194OCIsIjIxX3JlYWR5LW1lbW9yeSIsIjIyX3J1bi1tZW1vcnkiLCIyM191cGRhdGU1LW1lbW9yeSIsIjI1X3J1bi1jbGVhci1tZW1vcnkiLCIyNl9ydW4tMTBrLW1lbW9yeSIsIjMxX3N0YXJ0dXAtY2kiLCIzNF9zdGFydHVwLXRvdGFsYnl0ZXMiLCI0MV9zaXplLXVuY29tcHJlc3NlZCIsIjQyX3NpemUtY29tcHJlc3NlZCIsIjQzX2ZpcnN0LXBhaW50Il0sImRpc3BsYXlNb2RlIjoxfQ==)

Additionally, Qwik has a significant memory footprint and is by far the worst in this category based on the js web frameworks benchmark.

I am worried about how Qwik would perform in situations with large DOM or where DOM needs to be manipulated a lot. Think of a search result page where toggling filters can result in significant changes. Think of data grids, diagrams, and maps.

Would I struggle to make these kinds of use cases snappy using Quik?

Are runtime performance and memory usage improvements on the team's radar?

### Describe the solution you'd like

The ideal would be a combination of the startup characteristics of Qwik with the runtime characteristics of Svelte.

Quik already has a lot of knowledge of the components we write. Would anything prohibit us from having the same style of compile step that other web frameworks have to achieve more surgical DOM updates?

### Describe alternatives you've considered

—

### Additional context

Thank you for building Qwik and making the web better.

**Comment by wmertens** [comment]
That's exactly what's happening in the `build/v2` branch :)

**Comment by wmertens** [comment]
Closing this to keep the issue list limited, since we can't do anything more right now. Feel free to follow along in the v2 channel on discord

**Comment by DmitryEfimenko** [comment]
At work we're considering using Qwik for an upcoming project.
I've created a small proof of concept Qwik app and ported one feature from the existing app, which is a StencilJS app. The feature consists of approximately 10 components and renders a menu of items. The rendered DOM tree is fairly wide and deep. Clicking on some of the top level menu items shows a sub-menu, which replaces the top-level menu completely. So you can imagine that navigating from top-level menu to a sub-menu results in pretty much the whole DOM re-render since none of the previous elements are visible to the user.

In the StencilJS application that action is very fast - pretty much instant. However, the Qwik version has a noticeable delay. Please note that I made sure to follow [Qwik best practices](https://qwik.dev/docs/guides/best-practices/#best-practices) and tested it in both, dev and preview modes to make sure the source of performance issue is not the code.

Then I discovered [this Issue](https://github.com/QwikDev/qwik/issues/1404) and following that saw that Qwik v1 client-side performance is pretty poor compared to other frameworks.

<img width="654" height="731" alt="Image" src="https://github.com/user-attachments/assets/c0b694ec-b0be-4f1b-87bf-0d7a8900d8ec" />

Reading that Qwik v2 is expected to improve client-side performance, I've updated the proof of concept app to Qwik v2 (beta-28). Unfortunately I saw no improvements in client-side performance at all.

I see that the last comment here was from 2024. I assume the plans for improving client-side performance in v2 could have changed since then. Can you please clarify if this work is still pending or was it already implemented in v2?

I cannot share the repo since it's proprietary info, but I can't imagine I'm alone seeing these issues.

**Comment by wmertens** [comment]
@DmitryEfimenko can you perhaps share some performance traces of actions that are slow?

cc @Varixo

**Comment by DmitryEfimenko** [comment]
oh my gosh. While attempting to get the traces for you, I noticed a stupid issue in my code that was actually resulting in the performance issue. It was awaiting a set delay for analytics call between menu navigations rather than doing a fire-and-forget. I spent 3 days trying to fine-tune Qwik's code according to best practices thinking it's Qwik 😂. My bad. Disregard my message!

**Comment by wmertens** [comment]
Glad to hear all is well then 😂
