### ISSUE TITLE
State outside of the render tree

### ISSUE THREAD

**Issue by benjamingr** [BuilderIO/qwik#645]
### Is your feature request related to a problem?

Is there a blessed/good way to create state in Qwik outside of the render tree for logic?

I want to save code containing logic outside of the render tree and reuse it between a qwik web app and non-ui code and to simplify testing it.

### Describe the solution you'd like

A non-render-tree API that's an alternative for `useStore` like `observable` in MobX.

```js
const store = reactive({ x: 3, y: 5 }); 
```

This is similar to what `getOrCreateProxy` does in the code with the unit tests - the way some frameworks like MobX get around it is globality of the `map` argument (I'm not sure that's such a bad thing in this case since the globality is "transparent"). Alternatively if that's too hard or there is an ideological objection then a factory for it:

```js
const reactive = makeReactive(qInstance /*color my shed */);
const store = reactive({ x: 3, y: 5 });
```

Similarly, we'd want a way to listen to changes:

```js
autorun(() => console.log(store.x)
```

This would _not_ replace the render/framework aware hooks.

### Describe alternatives you've considered

From reading the code from what I can tell there is no current way to do this - I can theoretically pull in something like MobX and trigger changes in a store.

**Comment by nnelgxorz** [comment]
Would the Context APIs (createContext, useContext, useContextProvider) work for you here? They're not publicly documented but you can see their usage in the ToDo starter.

[Link](https://github.com/BuilderIO/qwik/tree/main/starters/apps/todo/src)

**Comment by benjamingr** [comment]
@nnelgxorz probably not since if I understand that example correctly it still uses `useStore` which you can use only inside the tree.

**Comment by mhevery** [comment]
Could we have an example of a test / use case you have in mind? I want to see if there are other ways to solve the problem.

**Comment by manucorporat** [comment]
For the reactivity outside the render tree, i have good news, all the subscriptions and reactivity are already decoupled from useStore(), and it's an standalone API, we could hook up, but it's not exposed yet

**Comment by shairez** [comment]
@manucorporat I agree with @benjamingr that this is important for managing stuff like "entities" or global data that should be  shared across components but without the need to put everything on the context. 

Does the example benji gave make sense? can we achieve this with the internal detached reactivity API manu mentioned?

**Comment by benjamingr** [comment]
@shairez I still owe Misko a gist for why I want DI/services as a concept - I think DI can be done _much nicer way_ than in React context and it'd make services easy/simple.

For example:

// myService.ts
```ts
// singleton duration by default, members are reactive by default
@service('UserService')
export class UserService { 
  username: string;
  // ...
  getUserData(username) {
    return fetch('/myApi', { ... }); 
  }
}
```

```ts
// Injects and builds UserService into the component based on parameters
// This can be made more or less magic depending on preferences
export const App = component$((@UserService service: UserService) => {
  // use the service here
  return <p>Hello Qwik</p>;
});
```

The important thing to notice here is that every service and its dependency chain is like the render tree in that reusability can be built in. Additionally the reason React DI sucks and requires hooks instead of just props is that DI needs to be baked into the framework for that syntax to work.

**Comment by benjamingr** [comment]
And of course this also solves Reactivity's globality which I think is what Manu didn't like in my example above

**Comment by mhevery** [comment]
I would love to see what you come up. Feel free to just paste it into this thread.

**Comment by manucorporat** [comment]
Sorry, thought i already share the data principles from qwik.

https://hackmd.io/SejfaQ53T1CYZgBIPAqRSQ#State-is-part-of-the-tree

Please feel free to reopen if you think this proposal can be put in a different way that fits the principles, or a strong argue about some of the principles.

But so far, in Qwik the state must be part of the tree, for technical reason but globals are in general something to avoid even in other templates when doing SSR.

The services seems like an antipattern in qwik, since it couples data with implementation

**Comment by DustinJSilk** [comment]
Hey @manucorporat  i'd like to add an argument for this where it would be very helpful to have stores created outside of the render tree.

A third party state management library built around Qwik may need to dynamically create stores that can feed back into the UI. These wouldn't be global stores but rather:
- Stores created outside of components
- Deeply nested within hooks, after async functions have returned

My example: I'm working on getting GraphQL working with Qwik which is built around a normalised cache of stores.
We can't add a new Qwik store from the render tree to the query each time we want to fetch data because the response must be normalised into an unknown number of stores after the data has been returned from the API.

Could there be a way to achieve this whilst still making it safe for most users? Maybe exporting the underlying proxy handler?

Thanks!
