### ISSUE TITLE
Support custom events

### ISSUE THREAD

**Issue by fgirardey** [BuilderIO/qwik#786]
### Is your feature request related to a problem?

Many web components dispatch custom events like `this.dispatchEvent(new CustomEvent('MDCDrawer:opened', {bubbles: true}))` but it seems that the Qwik event syntax cannot support those events.

### Describe the solution you'd like

Maybe something extending the syntax to `onAnyCustomEvent$={() => ...}` would be enough.

```tsx
export const App = component$(() => {
  const state = useStore({
    drawerOpened: false,
  });

  useClientEffect$(async () => {
    await import('@material/mwc-drawer');
  });

  return (
    <Host>
      <mwc-drawer
        type="modal"
        open={state.drawerOpened}
        onMDCDrawer:opened$={() => state.drawerOpened = false}
      >
        <div>
          <p>Drawer content!</p>
        </div>
        <div slot="appContent">
          <button onClick$={() => state.drawerOpened = !state.drawerOpened}>toggle menu</button>
        </div>
      </mwc-drawer>
    </Host>
  );
});
```

### Describe alternatives you've considered

I've considered to manually register the event listeners on client side hook but it's a lot of work.

**Comment by manucorporat** [comment]
try:
```
      <mwc-drawer
        type="modal"
        open={state.drawerOpened}
        on-MDCDrawer:opened$={() => state.drawerOpened = false}
      >
```

**Comment by fgirardey** [comment]
oh didn't knew that syntax variation, but it don't work in my case, i think this is because the event is literally `MDCDrawer:opened` and Qwik is doing a serialization of the event by changing the case of each letters.

**Comment by mhevery** [comment]
Adding more context.

There are several issues with having custom events:

1. JSX encoding
2. Camel case
3. Type system
4. qwikloader

## JSX Encoding
Let's say you have `MDCDrawer:opened` event type. The first problem is how to express that in code.
```typescript
  return <div 
    onClick$={() => null}
    on-kabab-case$={() => null}
    on-MDCDrawer:opened$={() => null}
    document:on-MDCDrawer:opened$={() => null} // <=== Not valid because JSX does not allow double `:`
    >Hello Qwik</div>;
});
```
produces:
```html
      <div
        on:click="app_component_div_onclick_ry0qi1xao5u.js#App_component_div_onClick_ry0QI1XaO5U"
        on:kabab-case="app_component_div_on_kabab_case_nsx73cvzhz0.js#App_component_div_on_kabab_case_Nsx73CVzHz0"
        on:-m-d-c-drawer:opened="app_component_div_on_mdcdrawer_opened_1_vf1jhz00hgw.js#App_component_div_on_MDCDrawer_opened_1_vF1jhZ00hGw"
      >
```

there is an additional problem with namespacing as `document:on-MDCDrawer:opened$` is not valid JSX because it has double `:`

## Camel Case

Next problem is that  `MDCDrawer:opened` has some upercase characters and attributes are all lowercase. 

## Type System

We need to extend the TypeScript type definition to allow for the new type. This should be straightforward, but I just don't remember how to re-open an interface definition in TypeScript.

## `qwikloader`

Finally, the `qwikloader` needs to be told about this event, as by default `qwikloader` only listens to the events that browsers emit. This can be done by passing explicit set of events here: https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/server/types.ts#L82


---

So it looks like that the only custom events we can listen to right now are ones which are all lowercase and which don't have a `:` in their name.

**Comment by manucorporat** [comment]
@mhevery Mind moving this context into the docs?

**Comment by manucorporat** [comment]
https://github.com/BuilderIO/qwik/pull/1212

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/pull/1212

**Comment by nterol** [comment]
Hello, 

I have read this discussion, but don't quite understand how to tell the qwikLoader to listen on my customEvent ? 
What file can I update and how, and should is use `document:on-[my-custom-event]` or can I use the `useDocumentEvent` ?
